styleName: "" # string: Style name (e.g. "Comic Book Style", "Watercolor Art")
description: "" # string: Brief description of visual character and usage

aiPrompts: # object: AI generator prompts (optional but recommended)
  basePrompt: "" # string: Main keywords defining the style
  negativePrompt: "" # string: What to avoid when generating
  styleKeywords: [] # array[string]: List of additional keywords

visualElements: # object: Main visual characteristics container
  colorPalette: # object: Color scheme definition
    primary: [] # array[string]: Main colors (hex, rgb, or descriptions)
    secondary: [] # array[string]: Secondary/accent colors
    background: "" # string: Dominant background color or type
    usageNotes: "" # string: How to apply colors
    saturation: "" # string: Saturation level (e.g. "high", "muted", "vibrant")
    contrast: "" # string: Contrast level (e.g. "high", "soft", "medium")

  lineArt: # object: Line and stroke characteristics
    style: "" # string: Line type (e.g. "bold outlines", "sketchy", "clean vector")
    weight: "" # string: Line thickness (e.g. "thin", "varied", "2-4px")
    color: "" # string: Line color
    texture: "" # string: Line texture (e.g. "smooth", "rough", "organic")
    edgeTreatment: "" # string: Edge handling approach

  composition: # object: Layout and arrangement (optional)
    layout: "" # string: Overall composition approach
    hierarchy: "" # string: Visual hierarchy system
    gridSystem: "" # string: Grid or structural system
    whitespace: "" # string: Use of negative space

  lighting: # object: Lighting characteristics
    type: "" # string: Lighting type (e.g. "soft diffused", "dramatic", "flat")
    direction: "" # string: Light direction (e.g. "top-left", "ambient", "multi-directional")
    intensity: "" # string/number: Light intensity
    shadows: # object: Shadow characteristics
      style: "" # string: Shadow style (e.g. "soft", "hard", "cel-shaded")
      color: "" # string: Shadow color
      opacity: "" # string/number: Shadow transparency
      offset: "" # string: Shadow offset/direction (optional)
    highlights: "" # string: Highlight rendering approach

  rendering: # object: Rendering technique
    technique: "" # string: Main technique (e.g. "digital painting", "3D render", "vector")
    texture: "" # string: Surface texture (e.g. "smooth", "grainy", "paper texture")
    detailLevel: "" # string: Detail level (e.g. "minimal", "moderate", "highly detailed")
    finish: "" # string: Surface finish (e.g. "matte", "glossy", "rough")
    printEffects: "" # string: Print-specific effects (optional)

  perspective: "" # string: Perspective type (e.g. "isometric", "frontal", "three-quarter view")
  # OR
  perspective: # object: Advanced perspective definition (optional)
    type: "" # string: Perspective type
    vanishingPoints: "" # string: Vanishing point treatment
    distortion: "" # string: Acceptable distortions
    depth: "" # string: Depth representation

  typography: # object: Typography integration (optional)
    integration: "" # string: How typography relates to design
    style: "" # string: Typography style characteristics
    weight: "" # string: Font weight preferences
    layout: "" # string: Text layout approach
    effects: "" # string: Typography effects
    sizes: "" # string: Size relationships

  mood: # object: Mood and atmosphere
    overall: "" # string: Overall mood (e.g. "playful", "dramatic", "serene")
    emotion: "" # string: Dominant emotion
    tempo: "" # string: Visual tempo (e.g. "dynamic", "calm", "energetic")
    energy: "" # string: Energy level (optional)
    keywords: [] # array[string]: Atmospheric keywords

  symbolism: # object: Symbolic elements (optional)
    common: [] # array[string]: Common symbols used
    figures: [] # array[string]: Typical figure types
    abstract: [] # array[string]: Abstract symbolic elements
    architectural: [] # array[string]: Architectural elements

postProcessing: # object: Post-production effects (optional)
  effects: [] # array[string]: Effect list (e.g. ["bloom", "grain", "vignette"])
  filters: "" # string: Color filters
  adjustments: {} # object: Additional settings (e.g. saturation, contrast)

stylePrecedents: [] # array[string]: Inspirational styles or artists (optional)

useCases: [] # array[string]: Best use cases for this style (optional)