# Audio Format Translations
# Translation of all 12 audio format names for multilingual NotebookLM generation

formats:
  przyjacielska_wymiana:
    pl: "Przyjacielska wymiana"
    en: "Friendly Exchange"
    es: "Intercambio Amistoso"
    pt: "Conversa Amigável"
    hi: "मैत्रीपूर्ण वार्तालाप"
    hi_romanized: "Maitreepurn Vartalaap"
    ja: "友好的な対話"
    ja_romanized: "Yuukouteki na Taiwa"
    ko: "친근한 대화"
    ko_romanized: "Chingeunhan Daehwa"
    de: "Freundlicher Austausch"
    fr: "Échange Amical"

  mistrz_i_uczen:
    pl: "Mistrz i Uczeń"
    en: "Master and Student"
    es: "Maestro y Estudiante"
    pt: "Mestre e Aluno"
    hi: "गुरु और शिष्य"
    hi_romanized: "Guru aur Shishya"
    ja: "師匠と弟子"
    ja_romanized: "Shishou to Deshi"
    ko: "스승과 제자"
    ko_romanized: "Seuseung-gwa Jeja"
    de: "Meister und Schüler"
    fr: "Maître et Élève"

  adwokat_i_sceptyk:
    pl: "Adwokat i Sceptyk"
    en: "Advocate and Skeptic"
    es: "Defensor y Escéptico"
    pt: "Advogado e Cético"
    hi: "समर्थक और संदेहवादी"
    hi_romanized: "Samarthak aur Sandehvaadi"
    ja: "擁護者と懐疑論者"
    ja_romanized: "Yougosha to Kaigironsha"
    ko: "옹호자와 회의론자"
    ko_romanized: "Onghoja-wa Hoeuiron-ja"
    de: "Anwalt und Skeptiker"
    fr: "Avocat et Sceptique"

  reporter_i_swiadek:
    pl: "Reporter i Świadek"
    en: "Reporter and Witness"
    es: "Periodista y Testigo"
    pt: "Repórter e Testemunha"
    hi: "रिपोर्टर और गवाह"
    hi_romanized: "Reporter aur Gawaah"
    ja: "記者と証人"
    ja_romanized: "Kisha to Shounin"
    ko: "기자와 증인"
    ko_romanized: "Gija-wa Jeung-in"
    de: "Reporter und Zeuge"
    fr: "Journaliste et Témoin"

  wspolczesny_i_klasyk:
    pl: "Współczesny i Klasyk"
    en: "Contemporary and Classic"
    es: "Contemporáneo y Clásico"
    pt: "Contemporâneo e Clássico"
    hi: "समकालीन और क्लासिक"
    hi_romanized: "Samkaaleen aur Classic"
    ja: "現代と古典"
    ja_romanized: "Gendai to Koten"
    ko: "현대와 고전"
    ko_romanized: "Hyeondae-wa Gojeon"
    de: "Zeitgenössisch und Klassisch"
    fr: "Contemporain et Classique"

  emocja_i_analiza:
    pl: "Emocja i Analiza"
    en: "Emotion and Analysis"
    es: "Emoción y Análisis"
    pt: "Emoção e Análise"
    hi: "भावना और विश्लेषण"
    hi_romanized: "Bhaavna aur Vishleshan"
    ja: "感情と分析"
    ja_romanized: "Kanjou to Bunseki"
    ko: "감정과 분석"
    ko_romanized: "Gamjeong-gwa Bunseok"
    de: "Emotion und Analyse"
    fr: "Émotion et Analyse"

  lokalny_i_globalny:
    pl: "Lokalny i Globalny"
    en: "Local and Global"
    es: "Local y Global"
    pt: "Local e Global"
    hi: "स्थानीय और वैश्विक"
    hi_romanized: "Sthaneey aur Vaishvik"
    ja: "地域と世界"
    ja_romanized: "Chiiki to Sekai"
    ko: "지역과 세계"
    ko_romanized: "Jiyeok-gwa Segye"
    de: "Lokal und Global"
    fr: "Local et Mondial"

  perspektywa_ona_on:
    pl: "Perspektywa Ona/On"
    en: "Her/His Perspective"
    es: "Su Perspectiva"
    pt: "Sua Perspectiva"
    hi: "उनका दृष्टिकोण"
    hi_romanized: "Unka Drishtikoon"
    ja: "彼/彼女の視点"
    ja_romanized: "Kare/Kanojo no Shiten"
    ko: "그/그녀의 관점"
    ko_romanized: "Geu/Geunyeo-ui Gwanjeom"
    de: "Ihre/Seine Perspektive"
    fr: "Sa Perspective"

  wyklad_filologiczny:
    pl: "Wykład filologiczny"
    en: "Philological Lecture"
    es: "Conferencia Filológica"
    pt: "Palestra Filológica"
    hi: "भाषाशास्त्र व्याख्यान"
    hi_romanized: "Bhaashashaastra Vyaakhyaan"
    ja: "言語学講義"
    ja_romanized: "Gengogaku Kougi"
    ko: "언어학 강의"
    ko_romanized: "Eoneohak Gang-ui"
    de: "Philologische Vorlesung"
    fr: "Conférence Philologique"

  fan_i_nowicjusz:
    pl: "Fan i Nowicjusz"
    en: "Fan and Newcomer"
    es: "Fan y Principiante"
    pt: "Fã e Iniciante"
    hi: "प्रशंसक और नवागंतुक"
    hi_romanized: "Prashansak aur Navaaganтuk"
    ja: "ファンと初心者"
    ja_romanized: "Fan to Shoshinsha"
    ko: "팬과 초보자"
    ko_romanized: "Paen-gwa Choboja"
    de: "Fan und Neuling"
    fr: "Fan et Débutant"

  glosa_do_przekladow:
    pl: "Glosa do przekładów"
    en: "Translation Commentary"
    es: "Comentario de Traducción"
    pt: "Comentário de Tradução"
    hi: "अनुवाद टिप्पणी"
    hi_romanized: "Anuvaad Tippanee"
    ja: "翻訳解説"
    ja_romanized: "Hon'yaku Kaisetsu"
    ko: "번역 해설"
    ko_romanized: "Beonyeok Haeseol"
    de: "Übersetzungskommentar"
    fr: "Commentaire de Traduction"

  komentarz_historyczno_literacki:
    pl: "Komentarz historyczno-literacki"
    en: "Historical-Literary Commentary"
    es: "Comentario Histórico-Literario"
    pt: "Comentário Histórico-Literário"
    hi: "ऐतिहासिक-साहित्यिक टिप्पणी"
    hi_romanized: "Aitihaasik-Saahityik Tippanee"
    ja: "歴史文学解説"
    ja_romanized: "Rekishi Bungaku Kaisetsu"
    ko: "역사문학 해설"
    ko_romanized: "Yeogsамunhak Haeseol"
    de: "Historisch-Literarischer Kommentar"
    fr: "Commentaire Historico-Littéraire"

# Usage notes:
# - Use the appropriate language code (pl, en, es, pt, hi, ja, ko, de, fr)
# - For scripts requiring romanization (Hindi, Japanese, Korean), both native and romanized versions are provided
# - These translations maintain the conceptual meaning while adapting to each language's cultural context