styleName: 2D Animation Style
description: Two-dimensional animation with flat, non-volumetric visual characteristics featuring frame-by-frame principles, cel-shaded aesthetics, clean geometric forms, and simplified lighting for clear character readability
aiPrompts:
  basePrompt: 2D animation, flat colors, cel animation, hand-drawn aesthetic, clean vector lines, cartoon style, frame by frame, traditional animation
  negativePrompt: 3D rendering, photorealistic, volumetric lighting, realistic shadows, 3D modeling, depth of field, live action, static image
  styleKeywords:
  - 2D animation
  - cel animation
  - traditional animation
  - cartoon
  - keyframes
  - tweening
  - squash and stretch
  - frame by frame
  - motion graphics
visualElements:
  colorPalette:
    primary:
    - bright red
    - electric blue
    - sunny yellow
    - vivid green
    - pure white
    secondary:
    - orange
    - purple
    - pink
    - turquoise
    - lime green
    background: animated backgrounds or cartoon environments
    usageNotes: Bright, clear colors suitable for animation
    saturation: high (clear, animation-friendly colors)
    contrast: high (clear character definition)
  lineArt:
    style: clean vector lines, hand-drawn line variation
    weight: medium to thick, uniform width
    color: black outlines or colored contours
    texture: smooth digital lines or slight hand-drawn texture
    edgeTreatment: smooth, precise vector edges
  lighting:
    type: flat lighting, three-point simplified setup
    direction: front-lit with minimal side lighting
    intensity: even, non-dramatic illumination
    shadows:
      style: simple flat shadows, minimal gradient
      color: darker versions of base colors
      opacity: medium opacity, clear definition
    highlights: minimal specular highlights, flat white accents
  rendering:
    technique: flat color fills, no gradients, clean edges
    texture: solid colors with minimal texture detail
    detailLevel: simplified forms, clear readable shapes
    finish: matte flat finish, no reflection or gloss
  perspective: simplified perspective suitable for animation
  mood:
    overall: dynamic, expressive, storytelling
    emotion: varies by animation style and story
    tempo: dynamic, movement-focused
    keywords:
    - dynamic
    - expressive
    - storytelling
    - movement
    - cartoon
  stylePrecedents:
  - Disney traditional animation
  - Japanese anime style
  - Chuck Jones Warner Bros cartoons
  - UPA animation studio
  - Flash/Adobe Animate productions
  - Nike motion graphics commercials
