styleName: 3D Clay Render Style
description: Professional 3D clay render style for design evaluation and form studies, featuring neutral monochromatic materials and uniform lighting
aiPrompts:
  basePrompt: 3D clay render, monochromatic shader, neutral material, uniform lighting, matte finish, form study, professional visualization
  negativePrompt: colorful, glossy, metallic, textured surfaces, decorative patterns, harsh shadows
  styleKeywords:
  - clay render
  - monochromatic
  - neutral shader
  - form study
  - technical
  - professional
visualElements:
  colorPalette:
    primary:
    - neutral gray
    - warm white
    - cool white
    - light beige
    secondary:
    - medium gray
    - off-white
    - light warm gray
    background: neutral gradient or solid white
    usageNotes: Neutral monochromatic tones for form evaluation
    saturation: minimal, desaturated
    contrast: subtle, form-focused
  lineArt:
    style: none - clean 3D forms
    weight: n/a
    color: n/a
    texture: smooth uniform material
    edgeTreatment: clean, precise geometry
  lighting:
    type: uniform studio lighting
    direction: multi-directional, even coverage
    intensity: balanced, shadowless
    shadows:
      style: minimal, soft
      color: neutral gray
      opacity: very subtle
    highlights: subtle, form-defining
  rendering:
    technique: 3D modeling with uniform clay material
    texture: smooth, uniform surface
    detailLevel: clean, precise forms
    finish: matte, consistent material
  perspective: technical angles, orthographic or slight isometric
  mood:
    overall: analytical, professional, clean
    emotion: neutral, focused, technical
    tempo: precise, methodical
    keywords:
    - professional
    - analytical
    - clean
    - technical
    - evaluative
  stylePrecedents:
  - Architectural visualization clay renders
  - Product design concept models
  - Industrial design form studies
  - KeyShot clay material renders
  postProcessing:
    effects:
    - ambient occlusion enhancement
    - subtle depth of field
    - uniform material application
    filters:
    - noise reduction for clean surfaces
    - contrast adjustment for form clarity
    adjustments:
    - highlight/shadow balance
    - material consistency check
    - neutral color grading
