styleName: 3D Textile Render Style
description: Technical 3D visualization focusing on photorealistic fabric simulation, yarn-level textures, and accurate textile material properties
aiPrompts:
  basePrompt: 3D textile render, knitted fabric texture, wool material, soft cloth simulation, fabric physics, realistic fiber structure
  negativePrompt: flat 2D, cartoon style, hard surfaces, metallic, glossy, plastic, low quality textures
  styleKeywords:
  - 3d textile
  - fabric render
  - knitted texture
  - wool material
  - soft cloth
  - fabric physics
visualElements:
  colorPalette:
    primary:
    - natural wool whites
    - cotton off-whites
    - linen beiges
    - raw cotton grays
    secondary:
    - dyed yarn colors
    - natural fiber browns
    - bleached whites
    - undyed grays
    background: neutral studio backgrounds
    usageNotes: Material-accurate textile colors based on real fabric properties
    saturation: natural fabric saturation levels
    contrast: realistic material contrast
  lineArt:
    style: none - fully rendered 3D
    weight: n/a
    texture: visible fabric weave and knit patterns
    edgeTreatment: soft fabric edges with realistic fraying
  lighting:
    type: soft studio lighting
    direction: diffused top-front lighting
    intensity: even material visualization lighting
    shadows:
      style: soft ambient occlusion
      color: neutral gray
      opacity: subtle
    highlights: natural fabric surface properties, matte finish
  rendering:
    technique: high-end 3D with fabric simulation
    texture: photorealistic textile materials - wool, cotton, knit, felt
    detailLevel: individual fiber visibility, knit patterns, fabric folds
    finish: matte fabric surfaces with subtle fuzz
  perspective: technical visualization perspective
  mood:
    overall: technical, precise, material-focused, realistic
    emotion: scientific accuracy, engineering precision, material truth
    tempo: detailed and methodical
    keywords:
    - technical
    - precise
    - realistic
    - material-accurate
    - scientific
  stylePrecedents:
  - Yarn-level fabric simulation research
  - Textile industry visualization
  - Fabric physics engines
  - Material science rendering