styleName: Aboriginal Dot Painting Style
description: Indigenous Australian dot painting style featuring intricate dot patterns, organic motifs, and earthy natural colors
aiPrompts:
  basePrompt: Aboriginal dot painting, intricate dot patterns, Indigenous art, dreamtime symbols, earthy tones
  negativePrompt: realistic shading, linear outlines, modern digital look, text elements
  styleKeywords:
  - aboriginal
  - dot painting
  - indigenous
  - pattern
  - earthy
visualElements:
  colorPalette:
    primary:
    - earth red
    - burnt orange
    - yellow ochre
    - brown
    secondary:
    - white
    - black
    - clay green
    background: earth-toned base (brown or red)
    usageNotes: Natural pigment colors reflecting the landscape
    saturation: medium
    contrast: medium
  lineArt:
    style: forms defined by dot outlines
    weight: n/a (dot size varies)
    color: white or yellow on dark; black or brown on light
    texture: dense pattern of repeated dots
    edgeTreatment: soft edges created by dot gradients
  lighting:
    type: flat (pattern-based imagery)
    direction: n/a
    intensity: n/a
    shadows:
      style: none
      color: n/a
      opacity: n/a
    highlights: none
  rendering:
    technique: hand-painted dots with sticks/brush
    texture: raised dots, tactile pattern
    detailLevel: high (thousands of dots form detail)
    finish: matte, textured
  perspective: flat, symbolic map-like
  mood:
    overall: spiritual, organic, intricate
    emotion: connection to land, storytelling
    tempo: rhythmic, meditative
    keywords:
    - spiritual
    - intricate
    - patterned
    - earthy
    - cultural
  stylePrecedents:
  - Papunya Tula art
  - Central Australian Indigenous dot paintings