styleName: Abstract Expressionism Style
description: Post-WWII American movement emphasizing spontaneous gestural painting (Action Painting) or contemplative color field compositions
aiPrompts:
  basePrompt: abstract expressionism, gestural brushwork, action painting, color field, spontaneous expression, large scale canvas
  negativePrompt: representational art, small scale, precise detail, controlled technique, european styles
  styleKeywords:
  - abstract expressionism
  - action painting
  - gestural
  - color field
  - spontaneous
visualElements:
  colorPalette:
    primary:
    - bold primary colors
    - earth tones
    - black and white
    secondary:
    - mixed intermediary colors
    - paint tube colors
    - accidental color mixing
    background: large color fields or gestural backgrounds
    usageNotes: Either bold gestural colors or subtle color field gradations
    saturation: varies (high for action painting, subtle for color field)
    contrast: varies by approach (high contrast gestures or subtle field)
  lineArt:
    style: gestural marks or no lines (color field)
    weight: varies dramatically with gesture
    color: paint colors, often mixed on canvas
    texture: heavy impasto or smooth color application
    edgeTreatment: rough gestural edges or soft color transitions
  lighting:
    type: no representational lighting
    direction: paint application creates light effects
    intensity: created by color intensity
    shadows:
      style: no representational shadows
      color: darker paint applications
      opacity: varies with paint thickness
    highlights: bright paint applications or canvas showing through
  rendering:
    technique: direct paint application, often alla prima
    texture: varies from smooth to heavy impasto
    detailLevel: abstract (no representational detail)
    finish: varies from matte to heavy texture
  perspective: no representational perspective
  mood:
    overall: emotional, expressive, spontaneous or contemplative
    emotion: raw expression or meditative calm
    tempo: energetic gesture or slow contemplation
    keywords:
    - emotional
    - expressive
    - spontaneous
    - contemplative
    - raw
  stylePrecedents:
  - Jackson Pollock drip paintings
  - Mark Rothko color fields