styleName: Geminism - Psychic Cartography
description: A style of abstract map-making that charts internal, psychological landscapes instead of physical locations. Lines represent streams of consciousness, colored regions represent emotional states, and abstract symbols mark significant memories, traumas, or moments of insight. The final piece is a unique and intricate map of a mind.
aiPrompts:
  basePrompt: psychic cartography, emotional map, mindscape, stream of consciousness lines, memory symbols, abstract geography, geminism
  negativePrompt: realistic map, physical geography, city plan, figurative art
  styleKeywords:
  - cartography
  - psychological
  - abstract
  - symbolic
  - internal
visualElements:
  colorPalette:
    primary:
    - a wide, symbolic palette where colors are tied to emotions (e.g., deep blues for melancholy, vibrant yellows for joy, harsh reds for anger)
    secondary:
    - neutral tones for "unexplored" or subconscious territories
    background: a textured surface like old paper, a nebula, or a biological cell texture
    usageNotes: Color is purely symbolic and is used to create an emotional topography.
    saturation: varies depending on the intensity of the emotion represented
    contrast: varies, creating areas of calm and areas of emotional conflict
  lineArt:
    style: a mix of fluid, wandering lines (thoughts) and sharp, jagged lines (anxieties), connecting various symbolic nodes
    weight: varies; thicker lines for dominant thought patterns, thinner for fleeting ideas
    color: ink-like black or colors that reflect the nature of the thought
    texture: hand-drawn, personal, like a diary entry
    edgeTreatment: lines can be smooth, broken, or frayed
  lighting:
    type: flat, diagrammatic, or with a subtle inner glow on certain "hotspots" of emotional intensity
    direction: n/a
    intensity: varies
    shadows:
      style: none, or subtle drop shadows on symbolic elements to give them importance
      color: light gray
      opacity: subtle
    highlights: certain nodes or regions might glow, representing epiphanies or core memories
  rendering:
    technique: mixed-media look, combining ink drawing, watercolor washes, and collaged symbols
    texture: paper texture, watercolor bleeds, layered elements
    detailLevel: highly intricate, filled with tiny symbols and annotations
    finish: matte, handcrafted, personal
  perspective: a top-down, 2D map perspective
  mood:
    overall: introspective, complex, personal
    emotion: a full range of human emotions, from joy to despair
    tempo: complex and multi-layered, inviting slow exploration
    keywords:
    - introspective
    - symbolic
    - complex
    - personal
    - emotional
  stylePrecedents:
  - Abstract Expressionism (for its emotionality)
  - Antique cartography and star charts
  - Mind mapping techniques