styleName: AI Gemini Bio Vellum
description: Digital biomechanical illustration style combining anatomical precision with ornate decorative elements. Features detailed organic forms rendered on aged parchment backgrounds with gold leaf accents and illuminated manuscript borders.
aiPrompts:
  basePrompt: biomechanical anatomical illustration, ornate decorative borders, gold leaf accents, vellum texture, detailed organic forms, illuminated manuscript style
  negativePrompt: simple illustration, cartoon, abstract, modern photography, steampunk, bright colors
  styleKeywords:
  - biomechanical
  - ornate
  - anatomical
  - manuscript
  - gilded
  - detailed
  - organic
visualElements:
  colorPalette:
    primary:
    - rich gold
    - deep crimson
    - warm ivory
    - sepia brown
    secondary:
    - muted greens
    - dark purple
    - black ink
    - silver highlights
    background: aged parchment texture with vellum appearance
    usageNotes: Warm, earthy medieval palette with gold accents for decorative elements
    saturation: moderate with high contrast gold details
    contrast: high
  lineArt:
    style: precise ink linework with ornate decorative borders and filigree
    weight: fine lines for anatomical details, bold for decorative elements
    color: sepia and black ink with gold accents
    texture: clean ink lines on textured parchment
    edgeTreatment: precise anatomical definition with flowing decorative flourishes
  lighting:
    type: soft directional lighting with ambient fill
    direction: top-down with subtle side lighting
    intensity: moderate with focused highlights
    shadows:
      style: soft realistic shadows for dimensional form
      color: warm brown tones
      opacity: medium
    highlights: warm gold reflections on metallic elements, subtle organic highlights
  rendering:
    technique: digital illustration simulating traditional illuminated manuscript techniques
    texture: smooth organic surfaces on textured parchment background
    detailLevel: high anatomical accuracy with intricate decorative patterns
    finish: matte parchment with selective gold leaf metallic accents
  perspective: scientific illustration perspective with flat decorative frame elements
  postProcessing:
    filters: subtle aging effects, parchment texture overlay
    adjustments: warm color grading, enhanced contrast for gold elements
    effects: soft glow on metallic accents, subtle vignette
  mood:
    overall: scholarly, reverent, mysterious
    emotion: intellectual curiosity, sacred knowledge, subtle unease
    tempo: contemplative, static
    keywords:
    - scholarly
    - anatomical
    - ornate
    - mysterious
    - detailed
    - reverent
  stylePrecedents:
  - Medieval illuminated manuscripts
  - Renaissance anatomical drawings
  - Biomechanical art movement