styleName: American Traditional Tattoo Style
description: Classic tattoo style with bold black outlines, limited color palette, and iconic nautical and Americana motifs
aiPrompts:
  basePrompt: American traditional tattoo, bold black outline, sailor tattoo, nautical motifs, limited colors
  negativePrompt: realistic shading, photorealistic, fine details, modern tattoo, watercolor
  styleKeywords:
  - traditional tattoo
  - bold outline
  - nautical
  - sailor
  - americana
visualElements:
  colorPalette:
    primary:
    - bold red
    - navy blue
    - black
    secondary:
    - yellow
    - green
    - skin tone
    background: skin tone or simple background
    usageNotes: Limited palette designed for skin application
    saturation: high (bold, vibrant colors)
    contrast: very high (bold black outlines)
  lineArt:
    style: very bold, thick black outlines
    weight: heavy, consistent thickness
    color: solid black
    texture: smooth, solid lines
    edgeTreatment: rounded ends, smooth curves
  lighting:
    type: flat lighting with minimal shading
    direction: even, front-lit
    intensity: consistent
    shadows:
      style: simple solid color shadows
      color: darker version of base color
      opacity: solid
    highlights: minimal, solid color highlights
  rendering:
    technique: simplified, iconic representation
    texture: smooth, flat colors
    detailLevel: moderate (clear iconic details)
    finish: flat, bold appearance
  perspective: simple, frontal views
  mood:
    overall: bold, iconic, maritime
    emotion: strength, tradition, pride
    tempo: strong, classic
    keywords:
    - bold
    - iconic
    - traditional
    - maritime
    - strong
  stylePrecedents:
  - Sailor Jerry Collins tattoos
  - Norman Collins flash sheets