styleName: Art Deco Style
description: 1920s-1940s decorative style featuring geometric patterns, symmetry, luxury materials, and elegant modernity with metallic accents
aiPrompts:
  basePrompt: art deco design, geometric patterns, symmetrical composition, luxury materials, elegant lines, metallic accents, 1920s style
  negativePrompt: organic curves, asymmetry, rustic materials, informal style, medieval elements
  styleKeywords:
  - art deco
  - geometric patterns
  - symmetrical
  - luxury
  - elegant
visualElements:
  colorPalette:
    primary:
    - gold metallic
    - black
    - cream white
    secondary:
    - silver chrome
    - deep red
    - royal blue
    background: elegant geometric patterns or luxury settings
    usageNotes: Rich, luxurious colors with metallic accents
    saturation: high (rich, elegant colors)
    contrast: high (dramatic black and gold contrasts)
  lineArt:
    style: geometric, symmetrical patterns
    weight: bold, confident lines
    color: metallic gold or silver outlines
    texture: smooth, polished surfaces
    edgeTreatment: sharp, precise geometric edges
  lighting:
    type: dramatic, luxury lighting
    direction: theatrical lighting emphasizing geometry
    intensity: bright, glamorous
    shadows:
      style: geometric, stylized shadows
      color: rich dark colors
      opacity: solid, dramatic
    highlights: brilliant metallic reflections
  rendering:
    technique: precise geometric illustration
    texture: polished metals, smooth surfaces, luxury materials
    detailLevel: high (intricate geometric patterns)
    finish: highly polished, reflective
  perspective: symmetrical, balanced compositions
  mood:
    overall: luxurious, elegant, sophisticated
    emotion: glamour, sophistication, modern elegance
    tempo: stately, confident
    keywords:
    - luxurious
    - elegant
    - sophisticated
    - glamorous
    - geometric
  stylePrecedents:
  - Chrysler Building architecture
  - 1920s luxury poster design