styleName: Art Brut Style
description: Raw, outsider art aesthetic created by marginalized individuals with spontaneous, rough textures, and uninhibited expression over polish
aiPrompts:
  basePrompt: art brut painting, naive art, raw textures, expressive, unrefined
  negativePrompt: polished, academic, realistic proportions, refined detail, trained artist, art school, conventional techniques, commercial art
  styleKeywords:
  - art brut
  - outsider art
  - raw
  - naive
  - expressive
visualElements:
  colorPalette:
    primary:
    - bold red
    - bright blue
    - sunny yellow
    secondary:
    - black outlines
    - muddy brown
    - gray
    background: plain canvas or paper
    usageNotes: Clashing colors applied with minimal blending
    saturation: high
    contrast: high
  lineArt:
    style: childlike scrawls or crude outlines
    weight: uneven, thick or scratchy
    color: black, or same as fill in places
    texture: rough, uneven strokes
    edgeTreatment: jagged, irregular edges
  lighting:
    type: non-realistic (flat or arbitrary color use)
    direction: n/a
    intensity: n/a
    shadows:
      style: none or abstract painted shadows
      color: n/a
      opacity: n/a
    highlights: none or raw canvas showing
  rendering:
    technique: impulsive brushwork, crayon scribbles
    texture: thick paint patches, visible strokes
    detailLevel: low (primitive forms)
    finish: matte, unrefined
  perspective: naive perspective (distorted or flat)
  mood:
    overall: raw, honest, chaotic
    emotion: intense emotion, innocence
    tempo: frantic or simplistic
    keywords:
    - raw
    - primitive
    - unfiltered
    - emotive
    - chaotic
  stylePrecedents:
  - Jean Dubuffet
  - Adolf Wölfli
  - Aloïse Corbaz
  - Henry Darger
  - Outsider art galleries