styleName: Atompunk Style
description: Post-WWII atomic age aesthetic featuring nuclear optimism, space age design, and retrofuturistic technology from 1945-1965
aiPrompts:
  basePrompt: atompunk design, atomic age, nuclear powered future, 1950s futurism, Googie architecture, space age
  negativePrompt: modern, dystopian, gritty, steampunk, medieval
  styleKeywords:
  - atompunk
  - atomic age
  - nuclear optimism
  - retrofuturism
  - Googie
visualElements:
  colorPalette:
    primary:
    - atomic red
    - turquoise
    - chrome
    - sunny yellow
    secondary:
    - mint green
    - coral pink
    - space blue
    background: bright optimistic sky or atomic facility
    usageNotes: Bright, optimistic colors of the atomic age
    saturation: high
    contrast: medium to high
  lineArt:
    style: sleek atomic age curves and angles
    weight: bold, confident lines
    color: black or chrome outlines
    texture: smooth, manufactured
    edgeTreatment: sharp angles meet smooth curves
  lighting:
    type: bright, optimistic lighting
    direction: clear, well-lit environments
    intensity: bright and cheerful
    shadows:
      style: minimal, stylized
      color: cool blue shadows
      opacity: light
    highlights: chrome gleams, atomic glow
  rendering:
    technique: mid-century illustration style
    texture: smooth surfaces, atomic motifs
    detailLevel: moderate with atomic age details
    finish: glossy, polished surfaces
  perspective: architectural and product showcase angles
  mood:
    overall: optimistic, progressive, atomic-powered
    emotion: confidence, progress, nuclear optimism
    tempo: upbeat, forward-moving
    keywords:
    - optimistic
    - atomic
    - progressive
    - confident
    - futuristic
  stylePrecedents:
  - Fallout game series aesthetics
  - 1950s World's Fair designs
  - Googie architecture