styleName: Aztec Codex Style
description: Stylized pre-Columbian Aztec art with flat figures, geometric symbols, and earthy colors on aged parchment
aiPrompts:
  basePrompt: Aztec codex illustration, flat ceremonial art, geometric glyphs, ancient manuscript
  negativePrompt: modern realism, perspective depth, shading, digital polish
  styleKeywords:
  - Aztec
  - codex
  - glyphic
  - ancient
  - flat
visualElements:
  colorPalette:
    primary:
    - ochre
    - earth brown
    - brick red
    - muted turquoise
    secondary:
    - black
    - white
    - olive green
    background: aged tan parchment
    usageNotes: Natural pigment tones with high-contrast outlines
    saturation: medium
    contrast: high
  lineArt:
    style: bold black outlines for figures and symbols
    weight: medium
    color: black or dark brown
    texture: solid, even strokes
    edgeTreatment: sharp, angular forms
  lighting:
    type: flat (symbolic art)
    direction: none
    intensity: n/a
    shadows:
      style: none (flat color areas)
      color: n/a
      opacity: n/a
    highlights: none
  rendering:
    technique: flat pigments on amate paper
    texture: slightly rough, fibrous paper
    detailLevel: moderate (stylized detail in patterns)
    finish: matte, hand-drawn
  perspective: flat, narrative panels
  mood:
    overall: ritualistic, ancient, symbolic
    emotion: mystery, cultural pride
    tempo: steady, formal
    keywords:
    - ancient
    - symbolic
    - ritual
    - geometric
    - earthy
  stylePrecedents:
  - Codex Borgia
  - Aztec temple murals