styleName: Baroque Tenebrism Style
description: Dramatic Baroque painting technique using extreme light-dark contrasts (chiaroscuro) to create emotional intensity and theatrical effects
aiPrompts:
  basePrompt: baroque painting, dramatic chiaroscuro, tenebrism, strong light-dark contrast, emotional intensity, theatrical composition
  negativePrompt: flat lighting, minimal contrast, simple composition, bright even lighting, modern style
  styleKeywords:
  - baroque
  - tenebrism
  - chiaroscuro
  - dramatic lighting
  - emotional intensity
visualElements:
  colorPalette:
    primary:
    - deep black
    - warm gold
    - rich brown
    secondary:
    - crimson red
    - olive green
    - ivory white
    background: dramatic dark backgrounds with selective illumination
    usageNotes: Rich, dark colors with dramatic light accents
    saturation: medium to high (rich oil painting colors)
    contrast: very high (extreme light-dark contrasts)
  lineArt:
    style: painterly edges defined by light and shadow
    weight: varies with lighting conditions
    color: defined by chiaroscuro rather than outlines
    texture: oil painting brushwork
    edgeTreatment: soft edges where light meets shadow
  lighting:
    type: dramatic directional lighting
    direction: strong single light source
    intensity: extreme contrasts between light and dark
    shadows:
      style: deep, dramatic shadows
      color: rich browns and blacks
      opacity: very opaque
    highlights: brilliant illumination on key subjects
  rendering:
    technique: oil painting with rich impasto
    texture: visible brushstrokes, oil paint texture
    detailLevel: high in illuminated areas, lost in shadows
    finish: rich oil paint finish
  perspective: dramatic angles emphasizing emotional impact
  mood:
    overall: dramatic, emotional, theatrical
    emotion: intensity, passion, drama
    tempo: dynamic, powerful
    keywords:
    - dramatic
    - emotional
    - theatrical
    - intense
    - powerful
  stylePrecedents:
  - Caravaggio paintings
  - Rembrandt portraits