styleName: Bauhaus Style
description: German design school philosophy emphasizing functionalism, simplicity, geometric forms, and the principle "form follows function"
aiPrompts:
  basePrompt: bauhaus design, functional simplicity, geometric forms, primary colors, clean lines, modernist, form follows function
  negativePrompt: ornate decoration, traditional ornament, complex details, historical styles, non-functional elements
  styleKeywords:
  - bauhaus
  - functional
  - geometric
  - simplicity
  - modernist
visualElements:
  colorPalette:
    primary:
    - red
    - blue
    - yellow
    secondary:
    - black
    - white
    - gray
    background: white or neutral geometric backgrounds
    usageNotes: Primary colors plus black, white, and gray
    saturation: high (pure primary colors)
    contrast: high (clear color separation)
  lineArt:
    style: clean, geometric lines
    weight: consistent, functional thickness
    color: black or primary color outlines
    texture: smooth, machine-made quality
    edgeTreatment: sharp, precise edges
  lighting:
    type: even, functional lighting
    direction: consistent, practical illumination
    intensity: clear, unadorned
    shadows:
      style: simple, geometric shadows
      color: gray
      opacity: consistent
    highlights: minimal, functional highlights
  rendering:
    technique: clean, geometric construction
    texture: smooth, industrial materials
    detailLevel: minimal (only essential elements)
    finish: matte, functional surfaces
  perspective: clear, functional perspective
  mood:
    overall: rational, functional, modern
    emotion: clarity, efficiency, progress
    tempo: steady, purposeful
    keywords:
    - rational
    - functional
    - modern
    - efficient
    - clear
  stylePrecedents:
  - Bauhaus school designs
  - Marcel Breuer furniture