styleName: Byzantine Art Style
description: Eastern Orthodox religious art featuring flat, frontal figures, gold backgrounds, hieratic composition, and spiritual rather than naturalistic representation
aiPrompts:
  basePrompt: byzantine art, gold background, frontal figures, religious icons, mosaic style, flat composition, orthodox christian art
  negativePrompt: realistic proportions, perspective, natural lighting, secular subjects, three-dimensional modeling
  styleKeywords:
  - byzantine
  - gold background
  - frontal figures
  - religious icons
  - hieratic
visualElements:
  colorPalette:
    primary:
    - gold leaf
    - deep blue
    - rich red
    secondary:
    - purple
    - white
    - black outlines
    background: gold leaf or rich colored backgrounds
    usageNotes: Rich, symbolic colors with extensive use of gold
    saturation: high (rich, symbolic colors)
    contrast: medium (gold backgrounds reduce contrast)
  lineArt:
    style: strong, defining outlines
    weight: consistent, bold outlines
    color: dark brown or black outlines
    texture: flat, linear treatment
    edgeTreatment: sharp, defined edges
  lighting:
    type: no naturalistic lighting, symbolic illumination
    direction: divine light emanating from figures
    intensity: spiritual radiance
    shadows:
      style: no shadows (spiritual realm)
      color: none
      opacity: none
    highlights: gold halos, divine radiance
  rendering:
    technique: flat, symbolic representation
    texture: smooth with mosaic-like quality
    detailLevel: high in symbolic details, simplified forms
    finish: matte with gold leaf
  perspective: no linear perspective, hierarchical scale
  mood:
    overall: spiritual, eternal, divine
    emotion: reverence, transcendence, devotion
    tempo: timeless, eternal
    keywords:
    - spiritual
    - eternal
    - divine
    - transcendent
    - hieratic
  stylePrecedents:
  - Hagia Sophia mosaics
  - Byzantine icon paintings