styleName: Celtic Knotwork Style
description: Intricate interlacing patterns with endless loops and symbolic motifs from medieval Insular art
aiPrompts:
  basePrompt: celtic knotwork, interlacing patterns, endless loops, medieval insular art, symbolic motifs, illuminated manuscript border
  negativePrompt: geometric, straight lines, modern, abstract, minimalist
  styleKeywords:
  - celtic
  - knotwork
  - interlacing
  - medieval
  - insular
  - symbolic
visualElements:
  colorPalette:
    primary:
    - '#8B4513'  # saddle brown
    - '#2F4F4F'  # dark slate gray
    - '#556B2F'  # dark olive green
    - '#000000'  # black
    secondary:
    - '#DAA520'  # goldenrod
    - '#CD853F'  # peru
    - '#483D8B'  # dark slate blue
    background: aged parchment
    usageNotes: Natural dyes and metals
    saturation: muted, earthy tones
    contrast: medium with gold accents
  lineArt:
    style: continuous interlacing
    weight: uniform, varying thickness
    color: black with gold highlights
    texture: hand-drawn quality
    edgeTreatment: seamless loops
  composition:
    layout: repeating patterns
    hierarchy: equal emphasis
    gridSystem: organic flow
    whitespace: filled with knots
  lighting:
    type: symbolic illumination
    direction: radiating from knots
    intensity: metallic highlights
    shadows: soft, under edges
    highlights: metallic gold
  mood:
    overall: mystical, timeless, spiritual
    emotion: eternity, connection, reverence
    tempo: flowing, continuous
    keywords:
    - mystical
    - timeless
    - spiritual
    - interwoven
    - eternal
  stylePrecedents:
  - Book of Kell manuscript
  - Lindisfarne Gospels
  - St. Chad Gospels
  - High crosses of Ireland
  - Pictish stone carvings