styleName: Celtic Knotwork Style
description: Intricate interlacing patterns with over-under alternation, endless loops, and basket weave motifs from medieval Insular art with protective symbolic meaning
aiPrompts:
  basePrompt: celtic knotwork, interlacing patterns, over-under weaving, endless knots, basket weave patterns, medieval insular art, symbolic motifs, illuminated manuscript border
  negativePrompt: geometric, straight lines, modern, abstract, minimalist
  styleKeywords:
  - celtic
  - knotwork
  - interlacing
  - medieval
  - insular
  - symbolic
visualElements:
  colorPalette:
    primary:
    - '#4169E1'  # woad blue
    - '#E1C16E'  # orpiment yellow
    - '#8B008B'  # lichen purple
    - '#000000'  # black ink
    secondary:
    - '#DC143C'  # red lead
    - '#228B22'  # copper green
    - '#F5F5DC'  # gypsum white
    - '#FF69B4'  # lichen pink
    background: aged parchment
    usageNotes: Medieval pigments and natural dyes
    saturation: vibrant medieval colors
    contrast: high contrast with no metallic elements
  lineArt:
    style: continuous interlacing
    weight: uniform, varying thickness
    color: black ink with colored highlights
    texture: hand-drawn quality
    edgeTreatment: seamless loops
  lighting:
    type: symbolic illumination
    direction: radiating from knots
    intensity: vibrant pigment highlights
    shadows:
      style: soft, under edges
      color: deeper tones of base colors
      opacity: subtle
    highlights: colored pigment accents
  rendering:
    technique: illuminated manuscript style
    texture: parchment with pigment application
    detailLevel: high intricacy in knotwork
    finish: medieval manuscript quality
  perspective: flattened, manuscript style
  mood:
    overall: mystical, timeless, spiritual
    emotion: eternity, connection, reverence
    tempo: flowing, continuous
    keywords:
    - mystical
    - timeless
    - spiritual
    - interwoven
    - eternal
  stylePrecedents:
  - Book of Kells manuscript
  - Lindisfarne Gospels
  - St. Chad Gospels
  - High crosses of Ireland
  - Pictish stone carvings