styleName: Cinematic Anime Realism Style
description: Hybrid style combining photorealistic detailed environments with simplified anime character design, featuring natural proportions, cinematic lighting, and atmospheric backgrounds reminiscent of Studio Ghibli and Makoto Shinkai works
aiPrompts:
  basePrompt: cinematic anime realism, cel-shaded, clean line art, realistic proportions, 2-3 tone shading, subdued colors, filmic lighting, shallow depth of field, photorealistic backgrounds, detailed environments, fine film grain, Makoto Shinkai inspired
  negativePrompt: no chibi, no cartoonish, no manga screentones, no hyper-detail, no tiny text, no watermark, no duplicate limbs, no extra fingers, no deformed hands, no noisy backgrounds
  styleKeywords:
  - cinematic anime
  - realistic proportions
  - cel-shaded
  - filmic lighting
  - shallow depth of field
  - Studio Ghibli inspired
  - Makoto Shinkai style
visualElements:
  colorPalette:
    primary:
    - subdued natural colors
    - warm indoor lighting
    - cool outdoor shadows
    - Shinkai blue tones
    secondary:
    - atmospheric fog colors
    - realistic skin tones
    - muted architectural colors
    background: realistic urban/rural environments with architectural detail
    usageNotes: Natural, subdued palette with selective color accents, low saturation overall
    saturation: low to medium
    contrast: high (cinematic lighting)
  lineArt:
    style: clean, precise line art with realistic proportions
    weight: medium weight, consistent
    color: "#333333"
    texture: smooth, no visible texture
    edgeTreatment: crisp but natural, no heavy outlines
  lighting:
    type: filmic lighting with realistic shadows and highlights
    direction: motivated by scene (window light, practical sources)
    intensity: high contrast with deep shadows
    shadows:
      style: 2-3 tone cel-shaded shadows
      color: cool blue or purple tones
      opacity: solid but not pitch black
    highlights: realistic specular highlights, lens flares
  rendering:
    technique: cel-shaded with realistic textures on backgrounds
    texture: smooth cel-shading on characters, detailed textures on environments
    detailLevel: high detail on backgrounds, moderate on characters
    finish: filmic with subtle grain
  postProcessing:
    effects:
    - film grain
    - lens flares
    - color grading
    - vignette
    - depth of field blur
    intensity: subtle to moderate
    filters: cinematic color correction, slight desaturation
  perspective: cinematic perspective with shallow depth of field
  mood:
    overall: cinematic, atmospheric, emotionally resonant
    emotion: melancholic, introspective, dramatic
    tempo: measured, contemplative
    keywords:
    - cinematic
    - realistic
    - atmospheric
    - filmic
    - natural
  stylePrecedents:
  - Studio Ghibli (Spirited Away, Princess Mononoke)
  - Makoto Shinkai (Your Name, Weathering With You)
  - Satoshi Kon (Paprika, Tokyo Godfathers)
  - Mamoru Hosoda (Wolf Children, The Girl Who Leapt Through Time)
  - Katsuhiro Otomo (Steamboy, Akira backgrounds)