styleName: Cinematic Documentary Realism Style
description: Realistic visual style mimicking documentary cinematography with natural lighting, authentic environments, and investigative atmosphere suitable for true events and historical documentaries
aiPrompts:
  basePrompt: cinematic documentary style, realistic lighting, authentic environments, investigative atmosphere, natural colors, documentary cinematography, realistic textures
  negativePrompt: fantasy, cartoon, anime, stylized, over-saturated, artificial lighting, unrealistic proportions
  styleKeywords:
  - cinematic
  - documentary
  - realistic
  - authentic
  - investigative
  - natural
visualElements:
  colorPalette:
    primary:
    - muted earth tones
    - natural greens
    - realistic browns
    secondary:
    - subdued blues
    - authentic grays
    - metallic silver
    background: natural outdoor environments, military installations, forest settings
    usageNotes: Natural, desaturated colors that convey authenticity and documentary realism
    saturation: low to medium
    contrast: natural contrast reflecting real-world lighting conditions
  lineArt:
    style: sharp, realistic definition with natural edges
    weight: defined by natural object boundaries
    color: integrated into realistic form
    texture: authentic material textures (metal, fabric, vegetation)
    edgeTreatment: crisp but natural edges as they appear in reality
  lighting:
    type: natural ambient lighting, practical light sources
    direction: realistic directional lighting from sun, moon, or artificial sources
    intensity: moderate, matching real-world conditions
    shadows:
      style: naturally cast shadows with realistic depth
      color: cool grays and muted tones
      opacity: realistic based on light source strength
    highlights: natural reflections and glints from surfaces
  rendering:
    technique: detailed realistic rendering with cinematic composition
    texture: authentic surface textures and materials
    detailLevel: high detail focused on environmental authenticity
    finish: natural, non-stylized surface treatments
  perspective: accurate perspective with documentary-style framing
  mood:
    overall: investigative, mysterious, authentic
    emotion: tension, curiosity, documentary intrigue
    tempo: measured, observational
    keywords:
    - authentic
    - investigative
    - mysterious
    - documentary
    - realistic
  stylePrecedents:
  - Documentary film cinematography
  - Investigative journalism photography
  - Historical recreation filmmaking