styleName: Comic Book Style
description: Classic comic book aesthetic featuring bold black outlines, Ben Day dots, vibrant flat colors, and dramatic compositions reminiscent of golden age superhero comics. Includes iconic elements like speech bubbles, sound effects, and sequential panel layouts with high contrast and exaggerated expressions.
aiPrompts:
  basePrompt: comic book illustration, bold black outlines, Ben Day dots, flat colors, speech bubbles, onomatopoeia, dramatic angles, vintage comics
  negativePrompt: photorealistic, smooth gradients, soft edges, blurry
  styleKeywords:
  - comic
  - Ben Day dots
  - flat colors
  - speech bubbles
  - onomatopoeia
  - bold outlines
  - vintage comics
visualElements:
  colorPalette:
    primary:
    - '#FF0000'
    - '#FFFF00'
    - '#0000FF'
    - '#00FFFF'
    - '#FF6600'
    - '#000000'
    - '#FFFFFF'
    secondary:
    - '#FFC107'
    - '#A52A2A'
    - '#8B4513'
    - '#008080'
    - '#999999'
    background: White or yellow with Ben Day dot patterns
    usageNotes: Colors should be flat and vivid with no gradients. Primary colors dominate foreground elements. Ben Day dots used for texture and shading effects.
    saturation: high
    contrast: high
  lineArt:
    style: bold black outlines
    weight: thick (2-6px)
    color: '#000000'
    texture: solid, no anti-aliasing
    edgeTreatment: sharp, high contrast
  lighting:
    type: dramatic
    direction: top-left
    intensity: high
    shadows:
      style: flat colored shadows with Ben Day dot patterns
      color: darker version of base color or black
      opacity: solid
    highlights: bold white or light color accents
  rendering:
    technique: digital illustration mimicking print
    texture: Ben Day dots, printed comic paper texture
    detailLevel: moderate with emphasis on clear forms
    finish: flat with visible ink strokes
  perspective: dynamic angles, often exaggerated
  mood:
    overall: dynamic and action-oriented
    emotion: exaggerated, dramatic, explosive
    tempo: fast-paced, energetic
    keywords:
    - action
    - dramatic
    - explosive
    - heroic
    - vintage
  postProcessing:
    effects:
    - Ben Day dots
    - ink outline
    - grain
    - misregistration
    filters: slight yellowing for vintage feel
    adjustments:
      saturation: high
      contrast: high
  stylePrecedents:
  - Jack Kirby
  - Steve Ditko
  - Roy Lichtenstein (pop art interpretation of comic aesthetics)
