styleName: Concept Art Sci-Fi Style
description: Dynamic sci-fi concept art look with dramatic lighting, futuristic cityscapes or technology, and a polished digital
  painting finish.
aiPrompts:
  basePrompt: science fiction concept art, futuristic city, digital painting, dramatic lighting, expansive scale
  negativePrompt: cartoonish, low detail, flat lighting, medieval themes
  styleKeywords:
  - sci-fi
  - concept art
  - futuristic
  - digital painting
  - dramatic
visualElements:
  colorPalette:
    primary:
    - neon blue
    - metallic gray
    - glowing cyan
    - steel silver
    secondary:
    - amber light
    - deep space black
    - violet sky
    background: futuristic skyline or starfield
    usageNotes: Cool tones dominate with pops of vibrant neon lighting
    saturation: medium
    contrast: high
  lineArt:
    style: painterly sketches painted over
    weight: n/a (lines hidden by painting)
    color: n/a
    texture: smooth digital, hard edges on tech
    edgeTreatment: sharp silhouettes, atmospheric fade
  lighting:
    type: dramatic cinematic lighting
    direction: multiple sources (city lights, backlights)
    intensity: high contrast (bright neon vs deep shadow)
    shadows:
      style: long shadows, diffused by haze
      color: cool blue or purple
      opacity: deep
    highlights: lens flares, neon glows on surfaces
  rendering:
    technique: digital painting with some photobash
    texture: smooth with textured brushes for atmosphere
    detailLevel: high in focal points (tech details), looser elsewhere
    finish: polished, cinematic look
  perspective: dynamic perspective (wide-angle vistas or low-angle hero shots)
  mood:
    overall: epic, futuristic, adventurous
    emotion: awe, excitement, curiosity
    tempo: dynamic, energetic
    keywords:
    - futuristic
    - epic
    - cinematic
    - detailed
    - atmospheric
  stylePrecedents:
  - Syd Mead (futurist designer)
  - Blade Runner concept art
