styleName: Constructivist Propaganda Style
description: Bold geometric designs with limited colors, dynamic diagonal compositions, strong typography elements, and revolutionary political messaging characteristic of Soviet agitprop
aiPrompts:
  basePrompt: constructivist poster, propaganda art, geometric shapes, bold typography, diagonal composition, revolutionary, photomontage, agitprop, soviet, red wedge
  negativePrompt: soft, organic, realistic, detailed, pastel
  styleKeywords:
  - constructivist
  - propaganda
  - geometric
  - revolutionary
  - bold
  - soviet
visualElements:
  colorPalette:
    primary:
    - '#FF0000'
    - '#000000'
    - '#FFFFFF'
    secondary:
    - '#CC0000'
    - '#333333'
    background: solid color blocks
    usageNotes: Limited palette, maximum impact
    saturation: maximum
    contrast: extreme
  lineArt:
    style: geometric, angular
    weight: bold, uniform
    color: black or contrasting
    texture: clean, sharp
    edgeTreatment: precise, mechanical
  lighting:
    type: flat, graphic
    direction: none - flat design
    intensity: n/a
    shadows:
      style: geometric drop shadows
      color: black
      opacity: solid
    highlights: none
  rendering:
    technique: vector-like precision
    texture: flat color blocks
    detailLevel: simplified to essentials
    finish: poster-like, graphic
  perspective: dynamic diagonals, forced perspective
  mood:
    overall: powerful, urgent, revolutionary
    emotion: determination, conflict, awakening
    tempo: dynamic, forceful
    keywords:
    - powerful
    - revolutionary
    - bold
    - urgent
    - authoritative
  stylePrecedents:
  - El Lissitzky
  - Alexander Rodchenko
  - Gustav Klutsis
  - Valentina Kulagina
  - Varvara Stepanova
  - Stenberg Brothers
  - Constructivist movement
