styleName: Cyberpunk Style
description: High-tech, low-life dystopian aesthetic with neon-lit cities, rain-slicked streets, and cybernetic enhancements
aiPrompts:
  basePrompt: cyberpunk cityscape at night, towering skyscrapers, neon signs, holographic advertisements, rain-slicked streets, flying vehicles, gritty urban decay, biomechanical cyborgs, high-tech low-life
  negativePrompt: bright daylight, sunny, rural, natural landscape, clean, utopian, minimalist
  styleKeywords:
  - cyberpunk
  - dystopian
  - neon-lit
  - futuristic
  - urban decay
  - high-tech
  - Blade Runner
  - Neuromancer
  - corporate hegemony
visualElements:
  colorPalette:
    primary:
    - electric blue
    - hot pink
    - neon purple
    - deep black
    secondary:
    - cyan
    - amber
    - metallic silver
    background: dark urban night sky
    usageNotes: Dark backgrounds with vivid neon accents and reflections on wet surfaces
    saturation: high for neons, low for backgrounds
    contrast: extreme
  lineArt:
    style: sharp architectural lines mixed with organic chaos
    weight: varied, often defined by neon lights
    color: neon outlines and black silhouettes
    texture: gritty, industrial
    edgeTreatment: crisp technology, rough urban decay
  lighting:
    type: dramatic neon and holographic lighting
    direction: multiple sources from signs and displays
    intensity: intense neon spots in dark environment
    shadows:
      style: deep, colored by neon reflections
      color: purple, blue, or colored by nearby lights
      opacity: heavy
    highlights: neon glows, wet reflections
  rendering:
    technique: photorealistic with digital elements
    texture: wet surfaces, rust, dirt, chrome, glass
    detailLevel: high detail in technology, gritty textures
    finish: glossy wet surfaces, matte dirt and grime
  perspective: street level looking up or aerial city views
  mood:
    overall: dark, oppressive, technologically overwhelming
    emotion: alienation, rebellion, anxiety
    tempo: chaotic, pulsing
    keywords:
    - dystopian
    - gritty
    - neon-soaked
    - claustrophobic
    - rebellious
  stylePrecedents:
  - Blade Runner (1982)
  - Neuromancer by William Gibson
  - Akira
  - Cyberpunk 2077