styleName: Dadaism Style
description: Anti-art movement using absurd juxtapositions, collage techniques, found objects, and rejection of traditional artistic values and logic
aiPrompts:
  basePrompt: dadaist art, absurd juxtaposition, collage, found objects, anti-art, chaotic composition, nonsensical elements
  negativePrompt: traditional composition, logical arrangement, classical beauty, coherent narrative, refined technique
  styleKeywords:
  - dadaism
  - anti-art
  - absurd
  - collage
  - found objects
visualElements:
  colorPalette:
    primary:
    - chaotic mixed colors
    - newspaper grays
    - random color combinations
    secondary:
    - found material colors
    - arbitrary color choices
    - clashing combinations
    background: collaged materials, newsprint, random textures
    usageNotes: No systematic color theory, random and found colors
    saturation: varies wildly (found materials)
    contrast: random, often jarring
  lineArt:
    style: cut edges, torn materials, random marks
    weight: varies by source material
    color: mixed from various sources
    texture: rough cut edges, found materials
    edgeTreatment: raw cut edges, torn paper
  lighting:
    type: inconsistent, from multiple sources
    direction: random, no unified lighting
    intensity: varies by source material
    shadows:
      style: drop shadows from layered materials
      color: arbitrary
      opacity: varies
    highlights: random reflections from found materials
  rendering:
    technique: collage, assemblage, found object combination
    texture: mixed textures from various sources
    detailLevel: varies by element (some detailed, some crude)
    finish: raw, unfinished appearance
  perspective: no unified perspective, chaotic viewpoints
  mood:
    overall: chaotic, rebellious, absurd
    emotion: rejection, rebellion, nonsense
    tempo: chaotic, unpredictable
    keywords:
    - chaotic
    - rebellious
    - absurd
    - anti-traditional
    - nonsensical
  stylePrecedents:
  - Marcel Duchamp readymades
  - Hannah Höch photomontages