styleName: Dadaism Style
description: WWI-era anti-art movement (1916-1924) originating in Zurich, using absurd juxtapositions, collage techniques, photomontage, found objects, chance operations, and rejection of traditional artistic values and logic
aiPrompts:
  basePrompt: dadaist art, absurd juxtaposition, collage, photomontage, found objects, anti-art, chaotic composition, nonsensical elements, chance operations, WWI era, 1916-1924
  negativePrompt: traditional composition, logical arrangement, classical beauty, coherent narrative, refined technique, systematic planning
  styleKeywords:
  - dadaism
  - anti-art
  - absurd
  - collage
  - photomontage
  - found objects
  - chance operations
visualElements:
  colorPalette:
    primary:
    - chaotic mixed colors
    - newspaper grays
    - random color combinations
    secondary:
    - found material colors
    - arbitrary color choices
    - clashing combinations
    background: collaged materials, newsprint, random textures
    usageNotes: No systematic color theory, random and found colors
    saturation: varies wildly (found materials)
    contrast: random, often jarring
  lineArt:
    style: cut edges, torn materials, random marks
    weight: varies by source material
    color: mixed from various sources
    texture: rough cut edges, found materials
    edgeTreatment: raw cut edges, torn paper
  lighting:
    type: inconsistent, from multiple sources
    direction: random, no unified lighting
    intensity: varies by source material
    shadows:
      style: drop shadows from layered materials
      color: arbitrary
      opacity: varies
    highlights: random reflections from found materials
  rendering:
    technique: collage, photomontage, assemblage, found object combination, typography experimentation
    texture: mixed textures from various sources
    detailLevel: varies by element (some detailed, some crude)
    finish: raw, unfinished appearance
  perspective: no unified perspective, chaotic viewpoints
  mood:
    overall: chaotic, rebellious, absurd
    emotion: rejection, rebellion, nonsense
    tempo: chaotic, unpredictable
    keywords:
    - chaotic
    - rebellious
    - absurd
    - anti-traditional
    - nonsensical
  stylePrecedents:
  - Marcel Duchamp readymades
  - Hannah Höch photomontages
  - Tristan Tzara sound poetry
  - Kurt Schwitters Merz collages
  - Raoul Hausmann photomontages