styleName: Decopunk Style
description: Retro-futuristic aesthetic combining Art Deco elegance with streamline moderne design, featuring sleek metallic forms and geometric luxury. Speculative vision of uninterrupted 1920s-30s technological progress creating a utopian chrome-and-gold future
aiPrompts:
  basePrompt: decopunk, art deco futurism, streamline moderne, elegant geometry, luxurious metals, 1930s glamour
  negativePrompt: rough textures, organic shapes, muted colors, primitive technology, rustic elements
  styleKeywords:
  - decopunk
  - art deco
  - streamline moderne
  - elegant
  - luxurious
visualElements:
  colorPalette:
    primary:
    - gold metallic
    - deep black
    - pearl white
    secondary:
    - silver chrome
    - ruby red
    - sapphire blue
    background: luxurious art deco interiors or streamlined cityscapes
    usageNotes: Rich, luxurious colors with metallic accents
    saturation: high (rich, glamorous colors)
    contrast: high (dramatic art deco contrasts)
  lineArt:
    style: precise geometric art deco patterns
    weight: bold, confident lines
    color: metallic gold or silver outlines
    texture: smooth, polished metallic surfaces
    edgeTreatment: sharp, precise geometric edges
  lighting:
    type: dramatic luxury lighting, spotlight effects
    direction: theatrical lighting emphasizing glamour
    intensity: bright highlights on metallic surfaces
    shadows:
      style: dramatic geometric shadows
      color: deep blacks or rich dark colors
      opacity: solid, dramatic
    highlights: brilliant metallic reflections and luxury glints
  rendering:
    technique: precise art deco illustration with metallic finishes
    texture: polished metals, smooth glass, luxurious fabrics
    detailLevel: high (intricate art deco ornamentation)
    finish: highly polished, reflective surfaces
  perspective: dramatic angles emphasizing art deco grandeur
  mood:
    overall: luxurious, elegant, sophisticated
    emotion: glamour, sophistication, refined power
    tempo: stately, magnificent
    keywords:
    - luxurious
    - elegant
    - sophisticated
    - glamorous
    - refined
  stylePrecedents:
  - 1930s Art Deco architecture
  - Streamline Moderne design
  - BioShock (Rapture aesthetics)
  - The Rocketeer
  - Sky Captain and the World of Tomorrow