styleName: Dia de los Muertos Art Style
description: Vibrant, colorful Mexican folk art style celebrating Day of the Dead with decorated skulls (calaveras), skeletons (calacas), marigolds (cempasúchil), and papel picado. Features bright, joyful colors representing celebration of life and memory, blending indigenous Aztec and Catholic influences.
aiPrompts:
  basePrompt: Dia de los Muertos art, sugar skull, calavera, marigold flowers, Mexican folk art, colorful skeletons, festive pattern, papel picado, ofrenda
  negativePrompt: scary, horror, gothic, sad, muted colors, minimalist
  styleKeywords:
  - Dia de los Muertos
  - sugar skull
  - calavera
  - Mexican folk
  - festive
  - marigold
  - cempasúchil
  - papel picado
  - ofrenda
visualElements:
  colorPalette:
    primary:
    - bright pink
    - orange (marigolds)
    - turquoise
    - sunny yellow
    secondary:
    - violet
    - lime green
    - black and white (for skeletons)
    background: black background or colorful, patterned background
    usageNotes: Extremely vivid, contrasting and joyful color palette.
    saturation: very high
    contrast: very high
  lineArt:
    style: bold, decorative lines, often with floral and swirling motifs
    weight: medium to thick, confident
    color: black or bright, contrasting colors
    texture: smooth, but with many small patterns
    edgeTreatment: clean, ornamental edges
  lighting:
    type: flat, graphic lighting
    direction: n/a
    intensity: n/a
    shadows:
      style: none or simple, flat shadows for form emphasis
      color: darker shade of base color
      opacity: solid
    highlights: none, flat colors
  rendering:
    technique: folk art, painting, paper cutouts (papel picado)
    texture: smooth surfaces with rich patterns, icing on skulls
    detailLevel: very high in ornaments and patterns
    finish: matte or slightly glossy (like icing)
  perspective: flat, frontal, symmetrical (especially for skulls)
  mood:
    overall: joyful, festive, celebrating
    emotion: joy, memory, life celebration, acceptance of death
    tempo: rhythmic, dance-like
    keywords:
    - festive
    - colorful
    - joyful
    - folk
    - celebrating
composition:
  layout: symmetrical, centered focal points
  balance: balanced with decorative elements
  focusPoints: skull faces, floral patterns, skeletal figures
  arrangement: ornamental, pattern-based, hierarchical
symbolism:
  primarySymbols:
  - decorated skulls (life celebration)
  - marigolds (guiding spirits home)
  - skeletal figures (acceptance of death)
  - papel picado (festive decoration)
  culturalMeaning: celebration of life and memory of deceased, spiritual connection between worlds
  colors:
    bright pink: joy and celebration
    orange: marigold guidance for spirits
    turquoise: protection and healing
    yellow: sun and life energy
typography:
  integration: decorative text elements, banner-style text
  style: ornamental, hand-lettered appearance
  weight: bold, readable
  decoration: floral embellishments, scroll work
technicalSpecifications:
  resolution:
    aspectRatio: flexible, commonly square or portrait
    minWidth: 1024
    minHeight: 1024
    unit: pixels
  orientation: flexible, works in both portrait and landscape
useCases:
  - Cultural celebrations and festivals
  - Memorial artwork and tributes
  - Decorative art and patterns
  - Educational cultural content
stylePrecedents:
- José Guadalupe Posada (calaveras prints)
- Mexican ofrenda altars
- traditional sugar skulls