styleName: Dieselpunk Style
description: Gritty dieselpunk aesthetic mixing 1940s industrial machinery with sci-fi elements, dark smoky atmospheres, and art deco-meets-industrial style
aiPrompts:
  basePrompt: dieselpunk art, industrial machinery, WWII era tech, zeppelins, dark gritty atmosphere
  negativePrompt: clean futuristic, high fantasy, nature-centric, minimalist
  styleKeywords:
  - dieselpunk
  - industrial
  - retro-futuristic
  - gritty
  - mechanical
visualElements:
  colorPalette:
    primary:
    - gunmetal gray
    - army green
    - sepia brown
    secondary:
    - oxidized brass
    - crimson
    - oil black
    background: smoky gray skies or factory interior
    usageNotes: Muted wartime tones with occasional red or brass accents; lots of gray and brown
    saturation: low
    contrast: medium (hazy atmosphere reduces contrast)
  lineArt:
    style: mechanical drafting meets comic outlines
    weight: medium, technical
    color: black or dark brown
    texture: slightly rough, soot-stained
    edgeTreatment: straight edges with rivet and bolt details
  lighting:
    type: dim, industrial lighting
    direction: harsh spotlights or searchlights through smoke
    intensity: low overall, bright in beams
    shadows:
      style: thick, smoke-diffused shadows
      color: brown-black
      opacity: heavy
    highlights: dull metal gleam on machinery
  rendering:
    technique: textured digital painting with grunge overlays
    texture: grime, rust, smoke effects
    detailLevel: high on machines and tech, moderate on backgrounds
    finish: matte with oily sheen on metal
  perspective: dramatic angles (low vantage of giant machines or aerial views)
  mood:
    overall: gritty, oppressive, retro-futuristic
    emotion: tension, determination
    tempo: tense, engine-pumping
    keywords:
    - gritty
    - industrial
    - retro
    - warlike
    - smoky
  stylePrecedents:
  - Sky Captain and the World of Tomorrow visuals
  - Dieselpunk art community works