styleName: Dieselpunk Style
description: Gritty dieselpunk aesthetic mixing 1920s-1950s industrial diesel-era machinery with retro-futuristic elements, Art Deco influences, dark smoky atmospheres, and militaristic WWII aesthetics
aiPrompts:
  basePrompt: dieselpunk art, industrial machinery, diesel engines, WWII era tech, zeppelins, Art Deco, retro-futuristic, propaganda art, pulp fiction style, dark gritty atmosphere
  negativePrompt: clean futuristic, high fantasy, nature-centric, minimalist
  styleKeywords:
  - dieselpunk
  - industrial
  - retro-futuristic
  - gritty
  - mechanical
  - Art Deco
  - militaristic
  - propaganda-style
visualElements:
  colorPalette:
    primary:
    - gunmetal gray
    - army green
    - sepia brown
    secondary:
    - oxidized brass
    - crimson
    - oil black
    - olive drab
    - steel blue
    background: smoky gray skies or factory interior
    usageNotes: Muted wartime tones with occasional red or brass accents; lots of gray and brown
    saturation: low
    contrast: medium to high (dramatic dieselpunk lighting creates strong contrasts)
  lineArt:
    style: mechanical drafting meets comic outlines
    weight: medium, technical
    color: black or dark brown
    texture: slightly rough, soot-stained
    edgeTreatment: straight edges with rivet and bolt details
  lighting:
    type: dim, industrial lighting
    direction: harsh spotlights, searchlights through smoke, propaganda poster lighting
    intensity: low overall, bright in beams
    shadows:
      style: thick, smoke-diffused shadows
      color: brown-black
      opacity: heavy
    highlights: dull metal gleam on machinery
  rendering:
    technique: textured digital painting with grunge overlays
    texture: grime, rust, smoke effects
    detailLevel: high on machines and tech, moderate on backgrounds
    finish: matte with oily sheen on metal
  perspective: dramatic angles (low vantage of giant machines or aerial views)
  mood:
    overall: gritty, oppressive, retro-futuristic, warlike, militaristic
    emotion: tension, determination
    tempo: tense, engine-pumping
    keywords:
    - gritty
    - industrial
    - retro
    - warlike
    - smoky
    - militaristic
    - propaganda-style
    - militant
  stylePrecedents:
  - Sky Captain and the World of Tomorrow visuals
  - The Rocketeer (1991) aesthetic
  - Iron Sky military retrofuturism
  - WWII propaganda poster art
  - 1930s-40s pulp magazine illustrations