styleName: Dystopian Futurism Style
description: Pessimistic vision of future featuring oppression, environmental catastrophe, social collapse, and technological surveillance in a dark, gritty world
aiPrompts:
  basePrompt: dystopian future, oppressive society, environmental disaster, surveillance state, dark atmosphere, industrial decay, authoritarian control
  negativePrompt: utopian, bright, clean, harmonious, peaceful, natural beauty, freedom
  styleKeywords:
  - dystopian
  - oppressive
  - surveillance
  - environmental collapse
  - authoritarian
visualElements:
  colorPalette:
    primary:
    - industrial gray
    - pollution brown
    - warning red
    secondary:
    - sickly yellow
    - toxic green
    - deep black
    background: polluted skies, industrial wastelands, oppressive architecture
    usageNotes: Muted, polluted colors suggesting environmental and social decay
    saturation: low to medium (desaturated, lifeless)
    contrast: high (harsh, oppressive contrasts)
  lineArt:
    style: harsh, angular lines suggesting oppression
    weight: heavy, imposing
    color: dark, oppressive outlines
    texture: rough, industrial surfaces
    edgeTreatment: sharp, threatening edges
  lighting:
    type: harsh artificial lighting or dim oppressive atmosphere
    direction: overhead surveillance lighting or dim ambient
    intensity: either blindingly harsh or oppressively dim
    shadows:
      style: deep, threatening shadows
      color: black or dark gray
      opacity: heavy, oppressive
    highlights: harsh spotlights or warning lights
  rendering:
    technique: gritty, realistic with industrial textures
    texture: rust, corrosion, pollution, decay
    detailLevel: high (showing decay and oppression)
    finish: matte, worn, deteriorated
  perspective: low angles emphasizing oppressive scale
  mood:
    overall: oppressive, hopeless, threatening
    emotion: fear, despair, resistance
    tempo: heavy, oppressive
    keywords:
    - oppressive
    - hopeless
    - threatening
    - decayed
    - authoritarian
  stylePrecedents:
  - 1984 totalitarian imagery
  - Mad Max post-apocalyptic world
  - Blade Runner cyberpunk aesthetics
  - Neuromancer literary foundation
  - The Matrix surveillance themes
  - Cyberpunk 2077 visual style
  - Minority Report surveillance state