styleName: Eco Botanical Style
description: Nature-inspired illustrations with botanical accuracy, environmental themes, and organic textures
aiPrompts:
  basePrompt: botanical illustration, eco-friendly art, nature inspired, organic forms, environmental theme, flora and fauna
  negativePrompt: industrial, artificial, urban, synthetic, geometric
  styleKeywords:
  - botanical
  - eco
  - nature
  - organic
  - environmental
  - sustainable
visualElements:
  colorPalette:
    primary:
    - forest green
    - earth brown
    - sky blue
    - sunlight yellow
    secondary:
    - moss
    - bark
    - leaf variations
    - flower tones
    background: natural paper or soft nature scenes
    usageNotes: Natural, earthy tones found in nature
    saturation: natural, not oversaturated
    contrast: gentle, natural light
  lineArt:
    style: delicate, botanical accuracy
    weight: varied, organic
    color: earth tones
    texture: hand-drawn quality
    edgeTreatment: soft, natural
  lighting:
    type: natural sunlight
    direction: dappled, filtered through leaves
    intensity: gentle, golden hour
    shadows:
      style: soft, organic
      color: cool earth tones
      opacity: translucent
    highlights: sun-kissed edges
  rendering:
    technique: botanical illustration mixed with modern eco-art
    texture: paper texture, organic materials
    detailLevel: high botanical accuracy
    finish: natural, handcrafted feel
  perspective: intimate nature views
  mood:
    overall: peaceful, conscious, harmonious
    emotion: connection, responsibility, wonder
    tempo: calm, meditative
    keywords:
    - sustainable
    - conscious
    - harmonious
    - natural
    - peaceful
