styleName: Eco-Botanical Style
description: Scientifically accurate botanical illustrations combined with environmental conservation messaging, sustainability themes, and ecological awareness
aiPrompts:
  basePrompt: eco-botanical illustration, environmental conservation, sustainability art, climate awareness, scientific illustration, ecological responsibility, botanical accuracy, nature conservation, environmental activism, sustainable living
  negativePrompt: industrial, artificial, urban, synthetic, geometric, pollution, waste, environmental destruction
  styleKeywords:
  - eco-botanical
  - conservation
  - sustainability
  - scientific
  - environmental
  - botanical
visualElements:
  colorPalette:
    primary:
    - forest green
    - earth brown
    - sky blue
    - sunlight yellow
    secondary:
    - sage green
    - dusty rose
    - warm ochre
    - lavender gray
    background: natural paper or soft nature scenes
    usageNotes: Natural, earthy tones found in nature
    saturation: natural, not oversaturated
    contrast: gentle, natural light
  lineArt:
    style: delicate, botanical accuracy
    weight: varied, organic
    color: earth tones
    texture: hand-drawn quality
    edgeTreatment: soft, natural
  lighting:
    type: natural sunlight
    direction: dappled, filtered through leaves
    intensity: gentle, golden hour
    shadows:
      style: soft, organic
      color: cool earth tones
      opacity: translucent
    highlights: sun-kissed edges
  rendering:
    technique: scientific illustration combined with environmental messaging
    texture: paper texture, organic materials
    detailLevel: high botanical accuracy
    finish: natural, handcrafted feel
  perspective: intimate nature views
  mood:
    overall: peaceful, conscious, harmonious
    emotion: environmental awareness, conservation, urgent, hopeful, responsibility, wonder
    tempo: calm, meditative
    keywords:
    - sustainable
    - conscious
    - harmonious
    - natural
    - peaceful
    - environmental awareness
    - conservation
    - urgent
    - hopeful
  stylePrecedents:
  - Maria Sibylla Merian botanical illustrations
  - John James Audubon nature art
  - Contemporary environmental illustration
  - Scientific conservation guides
  - Modern sustainability art