styleName: Expressionist Style
description: Emotional, distorted imagery with bold colors and dramatic angles conveying psychological intensity
aiPrompts:
  basePrompt: expressionist art, emotional distortion, bold brushstrokes, dramatic angles, psychological intensity
  negativePrompt: realistic, calm, peaceful, photographic, precise
  styleKeywords:
  - expressionist
  - emotional
  - distorted
  - dramatic
  - psychological
  - intense
visualElements:
  colorPalette:
    primary:
    - stark contrasts
    - deep reds
    - harsh yellows
    - midnight blues
    secondary:
    - acid greens
    - violent purples
    - stark whites
    background: turbulent, uneven color fields
    usageNotes: Clashing, emotional color choices
    saturation: very high or very low
    contrast: extreme
  lineArt:
    style: jagged, emotional
    weight: heavy, uneven
    color: black or contrasting colors
    texture: rough, aggressive
    edgeTreatment: angular, distorted
  lighting:
    type: dramatic, unnatural
    direction: multiple conflicting sources
    intensity: harsh
    shadows:
      style: deep, angular
      color: unnatural colors
      opacity: heavy
    highlights: stark, unsettling
  rendering:
    technique: rough brushwork
    texture: visible, aggressive strokes
    detailLevel: simplified for emotional impact
    finish: raw, unfinished feeling
  perspective: distorted, unsettling
  mood:
    overall: intense, psychological, disturbing
    emotion: anxiety, alienation, passion
    tempo: urgent, unstable
    keywords:
    - psychological
    - intense
    - emotional
    - disturbing
    - raw
  stylePrecedents:
  - Edvard Munch
  - Ernst Ludwig Kirchner
  - Egon Schiele
