styleName: Feature Animation 2D Classical
description: Classical 2D feature animation style rooted in Disney Golden Age tradition (1937-1942) with hand-drawn cel animation techniques, clean tapered lineart, soft shading, and simplified forms optimized for narrative storytelling

aiPrompts:
  basePrompt: feature film 2D animation style, clean tapered lineart, soft cel shading 1-2 levels, simplified materials, volumetric hair with single highlight, stylized background with clear depth planes, readable silhouettes and staging, emphasis on emotion and narrative
  negativePrompt: photorealism, skin pores, grain, heavy brush texture, 3D render, PBR, ray tracing, hard cel-shading, chromatic aberration, excessive neon colors, strong rim-light, lens distortion
  styleKeywords:
  - feature animation 2D
  - classical animation
  - clean lineart
  - soft shading
  - character design
  - story art
  - universal scene

visualElements:
  colorPalette:
    primary:
    - grays
    - broken browns
    - delicate pinks
    - ochres
    - caramels
    - warm grays
    secondary:
    - blues
    - graphites
    - muted greens
    background: gradient based backgrounds with atmospheric perspective
    usageNotes: Controlled palette with medium contrast, colors support scene without dominating
    saturation: medium (balanced for narrative)
    contrast: medium (clear without harshness)

  lineArt:
    style: clean closed lineart with tapering, varied line weight (outline > details)
    weight: outer stroke 20-40% thicker than inner, 1.0-3.5px at 2K resolution
    color: matching or darker than base colors
    texture: smooth vector-like quality
    edgeTreatment: rare breaks only in highlights to let form breathe

  composition:
    layout: clear staging with rule of thirds and leading lines
    hierarchy: hero has highest contrast and line weight
    gridSystem: foreground-midground-background layers
    whitespace: breathing room between silhouettes, avoid tangencies

  lighting:
    type: soft single source, simplified animation lighting
    direction: key light soft from front, weak fill, minimal rim
    intensity: medium, narrative-driven
    shadows:
      style: soft 1-2 gradient steps
      color: cooler than base color
      opacity: 60-80%
      offset: very subtle ambient occlusion at form contacts
    highlights: single soft highlight on materials

  rendering:
    technique: digital 2D animation, feature film quality
    texture: smooth without pores, suggested textures not realistic
    detailLevel: medium-high, optimized for readability
    finish: clean animation finish, no noise
    printEffects: none, clean digital output

  perspective:
    type: 35-50mm lens equivalent, no extreme distortions
    vanishingPoints: standard perspective rules
    distortion: minimal, only for dramatic effect
    depth: foreground-midground-background with overlapping planes and atmospheric haze

  typography:
    integration: clear separation from artwork
    style: readable, animation-friendly fonts
    weight: varied for hierarchy
    layout: follows animation composition rules
    effects: minimal, no interference with art

  mood:
    overall: narrative-driven, emotion-focused
    emotion: varies by scene requirements
    tempo: dynamic based on action
    energy: controlled for storytelling
    keywords:
    - storytelling
    - emotional
    - readable
    - dynamic
    - universal

postProcessing:
  effects:
  - subtle atmospheric fog
  - minimal dust particles
  - controlled smoke effects
  filters: none, maintain clean look
  adjustments:
    saturation: balanced for scene
    contrast: optimized for readability

stylePrecedents:
- Disney feature animation
- DreamWorks classical 2D
- Don Bluth productions
- Studio Ghibli clean style
- Warner Bros feature animation

useCases:
- Character portraits and designs
- Environment and prop design
- Narrative illustrations and key art
- Scene layouts and high-quality storyboards
- Action sequences and crowd scenes
- Interior and exterior environments

sceneControls:
  cameraShots:
  - ECU (Extreme Close Up)
  - CU (Close Up)
  - MCU (Medium Close Up)
  - MS (Medium Shot)
  - WS (Wide Shot)
  - EWS (Extreme Wide Shot)

  lightingModes:
    keyfill: soft key from front, weak fill, no rim
    overcast: diffused light, low contrast
    sunset: warm key, cool fill, long shadows
    nightNeon: dark base, local color spots, controlled saturation

  materialStyles:
    skin: smooth without pores, one soft highlight
    hair: volumetric strands, single shine accent
    fabric: repeatable patterns, no fiber detail
    metal: flat reflections, simplified highlights
    glass: contours plus 1-2 reflections, minimal distortion

  environmentElements:
    foliage: leaf masses as shapes, individual leaves only in foreground
    sky: simple gradations, clouds from large soft shapes
    water: flat reflections, simplified wave rhythm
    interiors: clean volumes, functional details without clutter
    props: weighted contours, soft shadows

  effectsGuidelines:
    atmospherics: fog, dust, smoke - subtle without grain
    energyGlow: sparingly, doesn't obscure readability
    speedLines: short directional, only in action

  multiCharacterStaging:
    spacing: breathing room between silhouettes
    eyelines: consistent gaze directions and heights
    hierarchy: hero has highest contrast and heaviest line

qualityChecks:
- Silhouette readability from thumbnail distance
- Consistent line thickness relative to scale
- Shadows match light source, no random rims
- Background doesn't compete with hero, clear hierarchy
- No photorealistic textures or noise
- Action line and movement vectors dominate over detail
- Consistent eye-lines and spacing in multi-character scenes