styleName: Flat Design Style
description: Minimalist digital design approach characterized by simple geometric elements, bold colors, typography focus, and complete absence of three-dimensional effects, shadows, or textures, emphasizing usability and clean visual hierarchy
aiPrompts:
  basePrompt: flat design illustration, minimalist, simple geometric shapes, bold solid colors, no gradients, clean vector graphics, 2D elements, Material Design inspired
  negativePrompt: 3D effects, shadows, textures, gradients, realistic, complex, bevels, embossing, drop shadows, depth
  styleKeywords:
  - flat design
  - minimal
  - simple
  - clean
  - modern
  - geometric
  - 2D
  - vector
  - Material Design
visualElements:
  colorPalette:
    primary:
    - bright blue
    - vibrant orange
    - emerald green
    - deep purple
    - flat red
    secondary:
    - pure white
    - light gray
    - charcoal gray
    background: solid bright colors or white
    usageNotes: Bold web-safe colors, Material Design palette, high saturation, no gradients
    saturation: high
    contrast: strong but balanced
  lineArt:
    style: minimal or none
    weight: uniform if present
    color: darker shade of fill color
    texture: none
    edgeTreatment: crisp, perfect vector edges
  lighting:
    type: none - completely flat
    direction: n/a
    intensity: n/a
    shadows:
      style: none or long shadows
      color: n/a or single flat color
      opacity: n/a or solid
    highlights: none
  rendering:
    technique: vector graphics
    texture: none
    detailLevel: minimalist
    finish: perfectly smooth and flat
  perspective: orthogonal or isometric, no depth
  mood:
    overall: modern, clean, friendly, efficient
    emotion: clarity, simplicity, approachability
    tempo: efficient, direct, uncluttered
    keywords:
    - modern
    - clean
    - simple
    - friendly
    - efficient
    - accessible
  stylePrecedents:
  - Microsoft Metro design language
  - Google Material Design
  - iOS 7 flat design revolution
  - Swiss design principles