styleName: Fresco Painting Style
description: Ancient wall painting technique on wet plaster creating matte finish integrated with architecture, often featuring classical or religious themes
aiPrompts:
  basePrompt: fresco painting, wall mural, wet plaster technique, matte finish, classical themes, architectural integration
  negativePrompt: canvas painting, glossy finish, modern themes, easel painting, detailed texture
  styleKeywords:
  - fresco
  - wall painting
  - plaster
  - matte finish
  - architectural
visualElements:
  colorPalette:
    primary:
    - earth ochre
    - ultramarine blue
    - burnt sienna
    secondary:
    - white lime
    - red oxide
    - green earth
    background: architectural wall surfaces or classical settings
    usageNotes: Earth pigments and mineral colors suitable for lime plaster
    saturation: medium (natural mineral pigments)
    contrast: medium (soft transitions)
  lineArt:
    style: classical drawing integrated with painting
    weight: consistent, classical proportions
    color: earth tone outlines
    texture: smooth plaster surface
    edgeTreatment: soft, integrated edges
  lighting:
    type: classical modeling with soft transitions
    direction: consistent classical light source
    intensity: moderate, classical
    shadows:
      style: soft, classical modeling
      color: earth tone shadows
      opacity: subtle, integrated
    highlights: soft, classical highlights
  rendering:
    technique: classical fresco buono on wet plaster
    texture: smooth plaster with slight granularity
    detailLevel: classical detail level
    finish: completely matte, integrated with wall
  perspective: classical linear perspective
  mood:
    overall: classical, permanent, architectural
    emotion: grandeur, permanence, classical beauty
    tempo: timeless, enduring
    keywords:
    - classical
    - permanent
    - architectural
    - timeless
    - monumental
  stylePrecedents:
  - Michelangelo Sistine Chapel
  - Pompeii wall paintings