styleName: Generative Abstraction Style
description: Non-representational abstract art created through algorithms, emphasizing pure visual exploration, emergent complexity from simple rules, and abstract expressionist outcomes from computational processes
aiPrompts:
  basePrompt: generative abstract art, non-representational, algorithmic abstraction, emergent patterns, abstract expressionist, computational aesthetics, pure visual exploration
  negativePrompt: figurative, representational, realistic objects, photographic, traditional composition, recognizable forms
  styleKeywords:
  - generative
  - algorithmic
  - abstract
  - non-representational
  - emergent
  - computational
  - abstract expressionist
  - procedural abstraction
visualElements:
  colorPalette:
    primary:
    - algorithmic color fields
    - computed gradients
    - parametric hues
    secondary:
    - emergent color relationships
    - systematic color progressions
    - abstract color harmonies
    background: algorithmic color fields or computed gradients
    usageNotes: Colors emerge from algorithmic processes, ranging from minimalist to complex palettes
    saturation: varies by algorithmic parameters
    contrast: computed abstract relationships
  lineArt:
    style: algorithmic curves, flowing forms, or geometric abstractions
    weight: varies by computational rules
    color: abstract color relationships
    texture: smooth computational forms or algorithmic textures
    edgeTreatment: precise digital or softly computed edges
  lighting:
    type: abstract computational lighting or flat abstraction
    direction: non-realistic or abstract lighting concepts
    intensity: varies for abstract effect
    shadows:
      style: abstract shadow forms or none
      color: computed abstract colors
      opacity: varies by aesthetic algorithm
    highlights: abstract computational highlights
  rendering:
    technique: algorithmic abstract generation
    texture: computed abstract textures or smooth fields
    detailLevel: varies from minimal to complex emergence
    finish: clean digital abstraction or computed roughness
  perspective: abstract space, non-Euclidean, or pure 2D abstraction
  mood:
    overall: contemplative, intellectually stimulating, aesthetically pure
    emotion: wonder at emergent beauty, meditative
    tempo: varies from static contemplation to dynamic emergence
    keywords:
    - abstract
    - contemplative
    - emergent
    - computational
    - non-representational
    - aesthetically pure
  stylePrecedents:
  - Vera Molnar
  - Manfred Mohr
  - Roman Verostko
  - Tyler Hobbs
  - Casey Reas
  - Frieder Nake