styleName: Geometric Abstract Style
description: Bold geometric shapes and patterns with mathematical precision and modernist aesthetic
aiPrompts:
  basePrompt: geometric abstract art, bold shapes, mathematical patterns, modernist design, precise geometry
  negativePrompt: organic, realistic, textured, hand-drawn, natural forms
  styleKeywords:
  - geometric
  - abstract
  - modernist
  - mathematical
  - precise
  - minimal
visualElements:
  colorPalette:
    primary:
    - primary colors
    - black
    - white
    secondary:
    - gray scales
    - complementary pairs
    background: solid colors or geometric patterns
    usageNotes: Bold, decisive color choices
    saturation: high or completely desaturated
    contrast: strong, clear divisions
  lineArt:
    style: precise, mathematical
    weight: uniform, calculated
    color: contrasting to fill
    texture: smooth, perfect
    edgeTreatment: sharp, exact
  lighting:
    type: flat, graphic
    direction: n/a
    intensity: even
    shadows:
      style: geometric shapes
      color: darker tones
      opacity: solid
    highlights: color blocks
  rendering:
    technique: vector-perfect precision
    texture: none or geometric patterns
    detailLevel: simplified to essential forms
    finish: clean, mathematical
  perspective: often impossible or multi-dimensional
  mood:
    overall: modern, intellectual, ordered
    emotion: clarity, structure, harmony
    tempo: static but dynamic through composition
    keywords:
    - modern
    - intellectual
    - ordered
    - precise
    - harmonious
  stylePrecedents:
  - Mondrian
  - Kandinsky
  - Bauhaus
