styleName: Gothic Art Style
description: Medieval art style featuring pointed arches, elongated figures, strong verticality, stained glass windows, and religious themes with hieratic composition
aiPrompts:
  basePrompt: gothic cathedral art, pointed arches, elongated figures, religious scenes, stained glass, medieval manuscript, vertical emphasis
  negativePrompt: renaissance realism, classical proportions, horizontal emphasis, secular themes, bright colors
  styleKeywords:
  - gothic
  - medieval
  - pointed arches
  - elongated figures
  - religious art
visualElements:
  colorPalette:
    primary:
    - deep blue
    - gold leaf
    - crimson red
    secondary:
    - rich purple
    - forest green
    - ivory white
    background: gold backgrounds or architectural settings
    usageNotes: Rich, jewel-like colors often with gold accents
    saturation: high (rich medieval pigments)
    contrast: medium to high (dramatic religious scenes)
  lineArt:
    style: linear, decorative outlines
    weight: consistent, defining contours
    color: dark outlines defining forms
    texture: flat, decorative treatment
    edgeTreatment: clean, defined edges
  lighting:
    type: symbolic rather than naturalistic lighting
    direction: divine light from above
    intensity: spiritual, not physical
    shadows:
      style: minimal, symbolic shadows
      color: darker versions of base colors
      opacity: subtle
    highlights: gold leaf highlights, divine radiance
  rendering:
    technique: flat, decorative painting
    texture: smooth with decorative patterns
    detailLevel: high in decoration, simplified in form
    finish: often matte with gold leaf accents
  perspective: hierarchical perspective, not linear
  mood:
    overall: spiritual, majestic, transcendent
    emotion: reverence, awe, devotion
    tempo: solemn, timeless
    keywords:
    - spiritual
    - majestic
    - transcendent
    - devotional
    - hierarchical
  stylePrecedents:
  - Chartres Cathedral windows
  - Gothic illuminated manuscripts