styleName: Gothic Fantasy Style
description: Dark gothic fantasy art style with ornate gothic architecture, dramatic shadows, and an eerie, otherworldly atmosphere
aiPrompts:
  basePrompt: gothic fantasy illustration, dark castle, gargoyles, dramatic chiaroscuro, haunting atmosphere
  negativePrompt: bright cheerful scenes, modern cityscapes, minimal detail, cartoonish tone
  styleKeywords:
  - gothic
  - dark fantasy
  - ornate
  - chiaroscuro
  - eerie
visualElements:
  colorPalette:
    primary:
    - black
    - charcoal gray
    - blood red
    secondary:
    - deep purple
    - midnight blue
    - silver
    background: stormy night sky or dim cathedral interior
    usageNotes: Mostly desaturated dark tones with occasional rich accent colors (e.g., red stained glass)
    saturation: low overall, with high-saturation accents
    contrast: high (very dark shadows vs piercing light)
  lineArt:
    style: elaborate, fine gothic detailing
    weight: varied (fine filigree to bold silhouettes)
    color: black or very dark ink
    texture: sharp, spiky architectural forms
    edgeTreatment: crisp edges on structures, wispy edges on fog/mist
  lighting:
    type: dramatic high-contrast (moonlight, torchlight)
    direction: side or backlighting to create silhouettes
    intensity: intense in beams, deep darkness elsewhere
    shadows:
      style: heavy, ornate shadows (through rose windows or railing)
      color: cold blue or purple tint
      opacity: opaque
    highlights: moon glows, candle flames highlighting details
  rendering:
    technique: digital or oil painting with rich texture
    texture: weathered stone, mist, velvet drapery
    detailLevel: high (architectural ornament, creature features)
    finish: matte overall with glints on wet or metallic surfaces
  perspective: dramatic angles (looking up at spires or down from heights to convey grandeur)
  mood:
    overall: dark, brooding, majestic
    emotion: fear, awe, melancholy
    tempo: slow, ominous
    keywords:
    - dark
    - ornate
    - haunting
    - majestic
    - mysterious
  stylePrecedents:
  - Gerald Brom (dark fantasy art)
  - Castlevania game art