styleName: Gothic Ink Autumn Etching Style
description: Gothic architecture with pointed arches, ribbed vaults, and flying buttresses rendered in traditional ink etching technique. Bold black outlines, variable line weight, dense crosshatching and stippling. Muted autumn colors with visible paper texture.
aiPrompts:
  basePrompt: gothic architecture, pointed arches, flying buttresses, medieval stonework, autumn foliage, bold black ink outlines, variable line weight, crosshatching and stippling, muted fall palette, coarse paper texture, traditional etching technique, overcast lighting, leaf-litter foreground
  negativePrompt: bright neon colors, smooth gradients, glossy finish, modern architecture, glass buildings, clean lines, digital art, high-saturation sky, perfectly clean vectors, hard cast shadows, photographic realism, symmetrical composition
  styleKeywords:
  - gothic architecture
  - medieval etching
  - ink crosshatch
  - autumn atmosphere
  - traditional engraving
  - variable line weight
  - pointed arches
visualElements:
  colorPalette:
    primary:
    - '#2B2B2B'  # black ink
    - '#C6B288'  # muted beige/ochre walls
    - '#A4B089'  # sage green background
    secondary:
    - '#D18A3A'  # burnt orange leaves
    - '#6B5A3C'  # umber shadows
    - '#8C7F61'  # greyish khaki fills
    - '#7A6B47'  # sepia tones
    - '#8B6F3D'  # burnt umber
    background: warm gray-beige paper
    usageNotes: Limited autumn palette, muted and faded colors with traditional ink tones
    saturation: low
    contrast: medium-low
  lineArt:
    style: brush-pen and dip-nib with variable weight
    weight: variable with sharp corners and frayed tails
    color: black ink
    texture: crosshatching in shadow masses, stippling for sky and mortar
    edgeTreatment: broken contour to imply age and wear, slight trapping leaving hairline light gaps
  lighting:
    type: overcast afternoon lighting
    direction: soft diffused light
    intensity: low key-to-fill ratio
    shadows:
      style: soft overcast, pooled in architectural recesses
      color: umber and khaki tones
      opacity: medium through crosshatching
    highlights: restrained, mostly line-preserved edges on stone details
  rendering:
    technique: ink crosshatch with sparse flat fills
    texture: coarse visible paper fiber, subtle ink bleed, traditional etching marks
    detailLevel: medium-high line density with architectural precision
    finish: matte with visible grain and speckle
  perspective: traditional Gothic perspective, low horizon, asymmetrical composition
  mood:
    overall: nostalgic, handcrafted, autumn melancholy, mysterious
    emotion: contemplative, aged, weathered, dramatic, imposing
    tempo: steady, methodical
    keywords:
    - nostalgic
    - weathered
    - handcrafted
    - autumn
    - mysterious
    - dramatic
    - imposing
    - medieval
  stylePrecedents:
  - Albrecht Dürer etchings
  - medieval manuscript illustrations
  - Piranesi architectural etchings
  - traditional india ink illustrations