styleName: Heroic Propaganda 1920s Style
description: Heroic propaganda poster style of the 1920s with simplified forms, strong contours, and limited color palette emphasizing revolutionary themes. Characterized by bold geometric shapes, dynamic diagonal compositions, and integrated typography as design element.
aiPrompts:
  basePrompt: heroic propaganda poster 1920s, constructivist influence, simplified geometric forms, strong bold contours, revolutionary poster art, limited color palette, diagonal dynamic composition, industrial aesthetic, worker hero, monumental scale, lithograph print style
  negativePrompt: detailed textures, soft edges, pastel colors, realistic rendering, complex shading, ornate decoration, photographic realism, organic shapes, Art Nouveau curves, impressionist brushwork
  styleKeywords:
  - heroic propaganda
  - constructivist
  - 1920s Soviet poster
  - simplified geometric forms
  - strong contours
  - revolutionary art
  - bold graphics
  - industrial aesthetic
  - worker heroism
  - monumental composition
  - lithograph style
  - avant-garde
visualElements:
  colorPalette:
    primary:
    - '#DC143C'  # revolutionary red
    - '#000000'  # bold black
    - '#FFFFFF'  # stark white
    secondary:
    - '#D4B896'  # workers' beige/kraft paper
    - '#808080'  # industrial grey
    - '#FFD700'  # accent gold
    background: solid color blocks, no gradients, paper texture acceptable
    usageNotes: Maximum 3-4 colors per composition, red as primary ideological color, high contrast essential
    saturation: high for red, desaturated for neutrals
    contrast: maximum, stark divisions
  lineArt:
    style: bold geometric contours, angular simplified forms, industrial precision
    weight: extra thick, uniform throughout
    color: pure black or reversed white on dark
    texture: clean vector-like, no texture within lines
    edgeTreatment: sharp angles, decisive corners, minimal curves
  lighting:
    type: flat graphic lighting, no realistic light sources
    direction: implied upward illumination for heroic effect
    intensity: uniform, poster-like flatness
    shadows:
      style: geometric drop shadows only if needed
      color: pure black or darker tone of base
      opacity: solid, no transparency
    highlights: minimal white accents for emphasis
  rendering:
    technique: lithograph/screen print simulation, vector-style clarity
    texture: optional subtle paper grain, otherwise completely flat
    detailLevel: reduced to essential symbolic elements only
    finish: matte poster finish, no glossy effects
  perspective: forced perspective from low angle for heroic effect, minimal depth with slight overlap for hierarchy
  mood:
    overall: heroic, revolutionary, urgent, triumphant
    emotion: determination, collective strength, forward momentum, optimism
    tempo: dynamic, march-like rhythm, visual percussion
    keywords:
    - heroic triumph
    - revolutionary fervor
    - collective power
    - industrial might
    - forward progress
    - monumental scale
    - urgent action
    - optimistic future
  stylePrecedents:
  - Alexander Rodchenko
  - El Lissitzky
  - Gustav Klutsis
  - Dmitry Moor
  - Vladimir Mayakovsky
  - Varvara Stepanova
  - Constructivist movement