styleName: Illuminated Manuscript Style
description: Medieval illuminated manuscript style with ornate initial letters, gold leaf accents, and dense decorative borders around text or images
aiPrompts:
  basePrompt: illuminated manuscript, medieval, ornate initials, gold leaf, calligraphic flourishes, parchment
  negativePrompt: modern typography, minimalist layout, plain design
  styleKeywords:
  - illuminated manuscript
  - medieval
  - ornate
  - gold leaf
  - calligraphy
visualElements:
  colorPalette:
    primary:
    - gold
    - royal blue
    - deep red
    - emerald green
    secondary:
    - black ink
    - ivory parchment
    - lapis blue
    background: aged parchment or vellum
    usageNotes: Rich pigments with metallic gold on a neutral parchment base
    saturation: medium-high
    contrast: medium (gold and colors vs parchment)
  lineArt:
    style: calligraphic scrollwork and outlines
    weight: thin to medium (varied in decoration)
    color: black or colored ink, plus gold accents
    texture: smooth, flowing lines
    edgeTreatment: decorative flourished ends
  lighting:
    type: flat (non-realistic illumination)
    direction: n/a
    intensity: n/a
    shadows:
      style: none (flat illustration)
      color: n/a
      opacity: n/a
    highlights: gold leaf shine catching light
  rendering:
    technique: hand-painted on vellum with egg tempera and gold leaf
    texture: slight paper grain, raised gold leaf areas
    detailLevel: very high (intricate borders and letters)
    finish: matte for colors, reflective for gold
  perspective: flat decorative layout (text and image on same plane)
  mood:
    overall: reverent, luxurious, scholarly
    emotion: devotion, admiration
    tempo: steady, deliberate
    keywords:
    - ornate
    - sacred
    - meticulous
    - historic
    - luxurious
  stylePrecedents:
  - Book of Kells
  - Medieval European manuscripts