styleName: Illuminated Manuscript Style
description: Medieval illuminated manuscript art style featuring decorative borders, gold leaf accents, flat perspective, religious iconography, and rich jewel-toned colors with hieratic composition
aiPrompts:
  basePrompt: illuminated manuscript, medieval book art, gold leaf decoration, flat perspective, religious iconography, ornate borders, jewel tones, hieratic composition
  negativePrompt: renaissance realism, classical proportions, horizontal emphasis, secular themes, bright colors
  styleKeywords:
  - illuminated manuscript
  - medieval book art
  - gold leaf
  - flat perspective
  - religious iconography
visualElements:
  colorPalette:
    primary:
    - deep blue
    - gold leaf
    - crimson red
    secondary:
    - rich purple
    - forest green
    - ivory white
    background: gold backgrounds or architectural settings
    usageNotes: Rich, jewel-like colors often with gold accents
    saturation: high (rich medieval pigments)
    contrast: medium to high (dramatic religious scenes)
  lineArt:
    style: linear, decorative outlines
    weight: consistent, defining contours
    color: dark outlines defining forms
    texture: flat, decorative treatment
    edgeTreatment: clean, defined edges
  lighting:
    type: symbolic rather than naturalistic lighting
    direction: divine light from above
    intensity: spiritual, not physical
    shadows:
      style: minimal, symbolic shadows
      color: darker versions of base colors
      opacity: subtle
    highlights: gold leaf highlights, divine radiance
  rendering:
    technique: flat, decorative painting
    texture: smooth with decorative patterns
    detailLevel: high in decoration, simplified in form
    finish: often matte with gold leaf accents
  perspective: hierarchical perspective, not linear
  mood:
    overall: spiritual, majestic, transcendent
    emotion: reverence, awe, devotion
    tempo: solemn, timeless
    keywords:
    - spiritual
    - majestic
    - transcendent
    - devotional
    - hierarchical
  stylePrecedents:
  - Book of Kells
  - Très Riches Heures du Duc de Berry
  - Gothic illuminated manuscripts