styleName: Impressionism Style
description: 19th-century painting movement capturing fleeting light and atmosphere with visible brush strokes, outdoor painting, and emphasis on light's changing qualities
aiPrompts:
  basePrompt: impressionist painting, visible brush strokes, plein air, natural light, atmospheric effects, loose technique, color mixing
  negativePrompt: precise details, smooth finish, studio lighting, dark colors, tight rendering
  styleKeywords:
  - impressionism
  - plein air
  - visible brush strokes
  - natural light
  - atmospheric
visualElements:
  colorPalette:
    primary:
    - light blue
    - sunny yellow
    - fresh green
    secondary:
    - violet shadows
    - orange sunlight
    - pink reflections
    background: outdoor natural settings with changing light
    usageNotes: Pure colors mixed optically, avoiding black and brown
    saturation: medium to high (pure color mixing)
    contrast: medium (soft light transitions)
  lineArt:
    style: broken color technique, no hard outlines
    weight: defined by color changes rather than lines
    color: color edges rather than drawn lines
    texture: visible brush strokes
    edgeTreatment: soft, broken edges
  lighting:
    type: natural outdoor lighting
    direction: changing sunlight throughout day
    intensity: bright natural light
    shadows:
      style: colored shadows (not black)
      color: complementary colors to light
      opacity: translucent, colorful
    highlights: pure color highlights
  rendering:
    technique: alla prima, wet-on-wet oil painting
    texture: visible canvas texture and brush marks
    detailLevel: impressionistic (capturing essence, not detail)
    finish: textured, painterly surface
  perspective: atmospheric perspective
  mood:
    overall: luminous, spontaneous, fresh
    emotion: joy in natural beauty, spontaneity
    tempo: quick, captured moment
    keywords:
    - luminous
    - spontaneous
    - fresh
    - atmospheric
    - natural
  stylePrecedents:
  - Claude Monet water lilies
  - Renoir outdoor scenes