styleName: Ink Wash Painting Style
description: East Asian ink wash (sumi-e) style with fluid brush strokes, minimal color, and harmony of empty space and bold ink
aiPrompts:
  basePrompt: ink wash painting, sumi-e, black ink on white, flowing brush strokes, Chinese calligraphy style
  negativePrompt: opaque thick paints, bright multi-colors, sharp mechanical lines, over-detailed forms
  styleKeywords:
  - ink wash
  - sumi-e
  - minimalist
  - fluid
  - calligraphic
visualElements:
  colorPalette:
    primary:
    - black ink
    secondary:
    - gray ink wash
    - white paper
    - red seal stamp
    background: white or off-white rice paper
    usageNotes: Monochrome with occasional red artist seal; relies on black-to-gray gradients of ink
    saturation: none (monochrome)
    contrast: high (black ink vs white paper)
  lineArt:
    style: bold yet fluid brush strokes
    weight: varied with brush pressure
    color: black (fading to gray in wash)
    texture: bleeding edges on absorbent paper
    edgeTreatment: soft where ink bleeds, crisp on quick strokes
  lighting:
    type: n/a (no representational lighting)
    direction: n/a
    intensity: n/a
    shadows:
      style: suggested by ink shading
      color: gray ink
      opacity: varied by wash
    highlights: paper left blank for highlights
  rendering:
    technique: brush and ink on paper (traditional sumi-e)
    texture: subtle paper grain, pooled ink gradients
    detailLevel: minimal (suggestive forms, negative space)
    finish: matte, natural media
  perspective: panoramic or bird's-eye (scroll painting style)
  mood:
    overall: serene, contemplative, natural
    emotion: tranquility, balance, introspection
    tempo: calm, flowing
    keywords:
    - minimalist
    - serene
    - fluid
    - natural
    - traditional
  stylePrecedents:
  - Chinese landscape scrolls
  - Sesshū Tōyō (sumi-e master)