styleName: Islamic Geometric Patterns Style
description: Complex, repeating geometric patterns based on mathematical principles, featuring symmetry and creating illusions of infinity
aiPrompts:
  basePrompt: islamic geometric patterns, complex symmetry, mathematical precision, repeating motifs, infinite patterns, arabesque
  negativePrompt: figurative art, random patterns, asymmetry, organic shapes, representational imagery
  styleKeywords:
  - islamic geometry
  - symmetry
  - mathematical
  - repeating patterns
  - infinite
visualElements:
  colorPalette:
    primary:
    - deep blue
    - gold leaf
    - white
    secondary:
    - emerald green
    - burgundy red
    - black outlines
    background: neutral or colored backgrounds showcasing geometric patterns
    usageNotes: Rich, saturated colors often with gold accents
    saturation: high (rich, jewel-like colors)
    contrast: high (clear pattern definition)
  lineArt:
    style: precise geometric lines forming complex patterns
    weight: consistent, mathematical precision
    color: dark outlines defining geometric forms
    texture: smooth, precise geometric construction
    edgeTreatment: sharp, mathematically precise edges
  lighting:
    type: even lighting to show pattern clarity
    direction: consistent illumination
    intensity: clear, pattern-revealing
    shadows:
      style: minimal shadows (focus on pattern)
      color: darker pattern colors
      opacity: subtle
    highlights: gold or bright accents in patterns
  rendering:
    technique: precise geometric construction
    texture: smooth with intricate pattern detail
    detailLevel: extremely high (complex mathematical patterns)
    finish: smooth, often with metallic accents
  perspective: flat, pattern-based composition
  mood:
    overall: spiritual, infinite, mathematical beauty
    emotion: contemplation, divine order, infinite complexity
    tempo: meditative, rhythmic
    keywords:
    - spiritual
    - infinite
    - mathematical
    - contemplative
    - divine
  stylePrecedents:
  - Alhambra palace patterns
  - Islamic manuscript illumination