styleName: Blueprint Urban Technical Style
description: Technical urban illustrations inspired by traditional engineering blueprints with precise blue line work on light backgrounds
aiPrompts:
  basePrompt: blueprint style, technical drawing, blue line art, urban architecture, engineering schematic, precise construction lines, architectural diagram
  negativePrompt: photorealistic, organic textures, perspective distortion, soft gradients, hand-drawn, sketchy lines
  styleKeywords:
  - blueprint
  - technical
  - urban
  - engineering
  - schematic
  - precise
visualElements:
  colorPalette:
    primary:
    - '#0066CC'
    secondary:
    - '#F8FAFE'
    accents:
    - '#FFFFFF'
    - '#CCE7FF'
    background: light blue tint or white
    usageNotes: Traditional blueprint colors with blue construction lines on light background
    saturation: medium to high
    contrast: high
  lineArt:
    style: precise technical construction lines
    weight: uniform thin to medium
    color: '#0066CC'
    texture: clean vector precision
    edgeTreatment: sharp technical angles and connections
  lighting:
    type: even ambient technical illumination
    direction: neutral top-down
    intensity: consistent even distribution
    shadows:
      style: precise geometric shadows
      color: darker blue or gray
      opacity: medium transparency
    highlights: crisp edge definition
  rendering:
    technique: technical vector construction
    texture: clean technical finish
    detailLevel: detailed technical accuracy
    finish: precise blueprint appearance
  perspective: orthographic technical projection
  mood:
    overall: precise, methodical, structured
    emotion: professional, technical, authoritative
    tempo: organized, systematic
    keywords:
    - precise
    - methodical
    - technical
    - professional
    - systematic
  stylePrecedents:
  - Engineering blueprints
  - Architectural technical drawings
  - CAD construction documents