styleName: Line Art Style
description: Clean, minimalist line drawings with bold outlines and no shading or color fills, characterized by contour-based forms typical in technical drawings and iconographic design
aiPrompts:
  basePrompt: line art, bold outline, simplistic, white background, 2d, no shading, no fill, outline only
  negativePrompt: photo, digital art, greyscale, painting, shading, color fill, gradient, texture, 3d rendering, shadows
  styleKeywords:
  - line art
  - outline
  - minimalist
  - clean lines
  - vector
visualElements:
  colorPalette:
    primary:
    - pure black
    secondary:
    - pure white
    background: pure white
    usageNotes: Black lines on white background only
    saturation: n/a
    contrast: maximum
  lineArt:
    style: bold outlines only
    weight: uniform thickness
    color: pure black
    texture: smooth, clean
    edgeTreatment: crisp, vector-like
  lighting:
    type: none
    direction: n/a
    intensity: n/a
    shadows:
      style: none
      color: n/a
      opacity: n/a
    highlights: none
  rendering:
    technique: clean vector-like lines
    texture: none
    detailLevel: simplified forms
    finish: flat, no texture
  perspective: varies, often frontal
  mood:
    overall: clean, minimal, modern
    emotion: neutral, clear
    tempo: static
    keywords:
    - minimal
    - clean
    - simple
    - modern
    - clear
  stylePrecedents:
  - Leonardo da Vinci technical drawings
  - Aubrey Beardsley illustrations
  - Modern logo design work
  - Technical diagram illustrations
  - Architectural blueprint style
  - Scientific illustration outlines