styleName: Minimalism Art Style
description: Extreme abstraction using simple geometric forms, limited colors, and focusing on the essential elements without unnecessary decoration
aiPrompts:
  basePrompt: minimalist art, simple geometric forms, clean composition, essential elements, reduced palette
  negativePrompt: ornate decoration, complex details, busy composition, many colors, realistic imagery
  styleKeywords:
  - minimalist
  - simple
  - geometric
  - clean
  - essential
visualElements:
  colorPalette:
    primary:
    - pure white
    - deep black
    - single accent color
    secondary:
    - neutral gray
    - natural beige
    - single primary color
    background: pure white or single color
    usageNotes: Extremely limited palette, often monochromatic
    saturation: low to none (except single accent)
    contrast: high (strong black/white relationships)
  lineArt:
    style: simple geometric lines, basic shapes
    weight: uniform, precise
    color: black or single color
    texture: completely smooth
    edgeTreatment: clean, sharp edges
  lighting:
    type: even, minimal lighting effects
    direction: ambient, non-directional
    intensity: subtle, understated
    shadows:
      style: minimal or no shadows
      color: light gray
      opacity: very subtle
    highlights: minimal, if any
  rendering:
    technique: simple geometric construction
    texture: smooth, no texture
    detailLevel: minimal (only essential elements)
    finish: flat, matte
  perspective: simple or no perspective
  mood:
    overall: calm, contemplative, pure
    emotion: serenity, focus, clarity
    tempo: static, meditative
    keywords:
    - calm
    - pure
    - focused
    - serene
    - essential
  stylePrecedents:
  - Donald Judd sculptures
  - Agnes Martin paintings
  - Dan Flavin fluorescent sculptures