styleName: Naive Art Style
description: Folk art style by self-taught artists featuring simple perspectives, intense colors, and childlike directness with abundant detail
aiPrompts:
  basePrompt: naive art, folk art, childlike perspective, intense colors, self-taught style, simple composition
  negativePrompt: academic technique, sophisticated perspective, muted colors, professional training, complex shading
  styleKeywords:
  - naive art
  - folk art
  - childlike
  - self-taught
  - simple
visualElements:
  colorPalette:
    primary:
    - bright red
    - vivid blue
    - sunny yellow
    secondary:
    - grass green
    - purple
    - orange
    background: simple flat colors or patterns
    usageNotes: Intense, saturated colors used intuitively
    saturation: very high (bold, pure colors)
    contrast: high (bright colors against each other)
  lineArt:
    style: simple, direct outlines
    weight: consistent, moderate thickness
    color: dark outlines or color boundaries
    texture: hand-drawn quality, slight irregularities
    edgeTreatment: simple, clean edges
  lighting:
    type: flat, even lighting (no sophisticated shading)
    direction: front-lit, minimal shadows
    intensity: bright, cheerful
    shadows:
      style: simple, flat shadows if any
      color: darker version of base color
      opacity: solid
    highlights: minimal, simple bright spots
  rendering:
    technique: direct, intuitive application
    texture: flat colors with simple patterns
    detailLevel: high in some areas (obsessive detail), simple in others
    finish: flat, matte appearance
  perspective: flattened or incorrect perspective, childlike spatial relationships
  mood:
    overall: cheerful, innocent, direct
    emotion: joy, simplicity, honesty
    tempo: peaceful, content
    keywords:
    - cheerful
    - innocent
    - direct
    - honest
    - joyful
  stylePrecedents:
  - Henri Rousseau jungle paintings
  - Grandma Moses rural scenes