styleName: Neoclassicism Style
description: A mid-18th century style that drew inspiration from the art of classical antiquity (Greece and Rome), emphasizing order, reason, and heroism. It was a reaction against the ornate and frivolous Rococo style.
aiPrompts:
  basePrompt: neoclassicism painting, classical antiquity, heroic scene, Roman architecture, sculptural figures, Jacques-Louis David style, historical painting
  negativePrompt: rococo, ornate, frivolous, pastel colors, loose brushwork, emotional chaos
  styleKeywords:
  - neoclassicism
  - classical
  - heroic
  - orderly
  - historical
  - rational
visualElements:
  colorPalette:
    primary:
    - somber reds
    - deep blues
    - stone grays
    - stark whites
    secondary:
    - gold
    - bronze
    - olive green
    background: classical architecture, stark interiors
    usageNotes: A severe, controlled palette emphasizing form and structure.
    saturation: medium, often subdued
    contrast: high, with dramatic chiaroscuro
  lineArt:
    style: sharp, clear, and defined contours, emphasizing drawing (disegno)
    weight: precise and controlled
    color: integrated into the form, not a separate outline
    texture: smooth, polished
    edgeTreatment: sharp, sculptural edges
  lighting:
    type: clear, strong, often theatrical lighting
    direction: strong directional source, creating sharp shadows
    intensity: high contrast, like stage lighting
    shadows:
      style: sharp and well-defined, carving out forms
      color: dark browns and grays
      opacity: heavy, solid
    highlights: clear and bright on key figures and objects
  rendering:
    technique: smooth, polished oil painting with invisible brushstrokes
    texture: surfaces appear like polished marble or stone
    detailLevel: very high, with attention to historical accuracy
    finish: smooth, highly finished, almost enamel-like
  perspective: logical and clear, often using a stage-like composition
  mood:
    overall: serious, heroic, rational
    emotion: civic virtue, duty, sacrifice, stoicism
    tempo: static, posed, monumental
    keywords:
    - heroic
    - rational
    - serious
    - moral
    - classical
  stylePrecedents:
  - Jacques-Louis David
  - Jean-Auguste-Dominique Ingres
  - Antonio Canova