styleName: Film Noir Style
description: Dark, high-contrast cinematographic scenes with dramatic shadows, venetian blind lighting, and sophisticated urban atmosphere
aiPrompts:
  basePrompt: film noir style, dramatic shadows, venetian blinds, urban night, cinematographic lighting, high contrast black and white
  negativePrompt: bright, cheerful, colorful, soft, rural, cartoonish, oversaturated
  styleKeywords:
  - noir
  - cinematographic
  - dramatic
  - urban
  - shadows
  - mysterious
  - sophisticated
visualElements:
  colorPalette:
    primary:
    - deep blacks
    - stark whites
    - charcoal gray
    secondary:
    - silver highlights
    - amber streetlight
    - subtle smoke gray
    background: dark urban settings with architectural elements
    usageNotes: Predominantly monochromatic with subtle warm lighting accents
    saturation: very low, desaturated
    contrast: extreme high contrast
  lineArt:
    style: sharp, angular, architectural
    weight: bold outlines with fine shadow details
    color: deep black with gray gradations
    texture: clean lines with atmospheric shadows
    edgeTreatment: precise, cinematographic clarity
  lighting:
    type: harsh directional with soft ambient
    direction: low angle, venetian blind patterns, window shadows
    intensity: extreme contrast between light and dark
    shadows:
      style: deep, geometric, venetian blind patterns
      color: pure black with gray gradations
      opacity: solid dramatic shadows with subtle gradients
    highlights: harsh, selective, cinematographic
  rendering:
    technique: high contrast cinematographic illustration
    texture: smooth with atmospheric depth
    detailLevel: selective focus on mood and atmosphere
    finish: sophisticated film noir quality
  perspective: dramatic angles, Dutch tilts, urban architecture
  mood:
    overall: mysterious, sophisticated, atmospheric
    emotion: suspense, intrigue, psychological tension
    tempo: contemplative, suspenseful
    keywords:
    - mysterious
    - sophisticated
    - atmospheric
    - psychological
    - contemplative
    - urban
  stylePrecedents:
  - Classic film noir cinematography
  - Film noir movie posters
  - Urban night photography
  - Architectural shadow studies