styleName: Op Art Style
description: Optical illusion art using abstract geometric patterns to create visual effects of movement, vibration, and depth perception
aiPrompts:
  basePrompt: op art, optical illusion, geometric patterns, moire pattern, black and white abstraction, kinetic art, Bridget Riley style, repetitive lines, visual vibration
  negativePrompt: figurative, realistic, color photography, soft edges, painterly, blurred, organic shapes
  styleKeywords:
  - op art
  - optical illusion
  - kinetic
  - geometric
  - pattern
  - dizzying
  - moire
  - vibrating
visualElements:
  colorPalette:
    primary:
    - '#000000'
    - '#FFFFFF'
    secondary:
    - '#FF0000'
    - '#0000FF'
    - '#FFFF00'
    background: integrated pattern element
    usageNotes: predominantly black and white for maximum contrast, occasionally bright complementary colors
    saturation: maximum
    contrast: extremely high
  lineArt:
    style: precise geometric repetition
    weight: uniform
    color: high contrast
    texture: smooth vector
    edgeTreatment: sharp precise edges
  lighting:
    type: flat uniform
    direction: none
    intensity: high
    shadows:
      style: none
      color: none
      opacity: 0
    highlights: none
  rendering:
    technique: precise vector graphics
    texture: smooth mathematical
    detailLevel: high precision
    finish: clean digital
  perspective: flat plane with illusion depth
  mood:
    overall: dynamic disorienting
    emotion: hypnotic fascination
    tempo: vibrating pulsating
    keywords:
    - hypnotic
    - vibrating
    - disorienting
    - geometric
    - illusion
    - kinetic
  stylePrecedents:
  - Victor Vasarely
  - Bridget Riley
  - Jesus Rafael Soto