styleName: Pen and Ink Drawing Style
description: Traditional drawing technique using pen and black ink, characterized by precise lines, crosshatching, and high contrast
aiPrompts:
  basePrompt: pen and ink drawing, crosshatching, line art, black ink, precise linework
  negativePrompt: color, painting, soft edges, blurred lines, photographic
  styleKeywords:
  - pen and ink
  - crosshatching
  - line art
  - black ink
  - precise
visualElements:
  colorPalette:
    primary:
    - black ink
    - paper white
    secondary:
    - gray (created by line density)
    background: white or cream paper
    usageNotes: Monochromatic, using only black ink on white paper
    saturation: none (black and white only)
    contrast: very high (black ink on white paper)
  lineArt:
    style: precise pen lines, crosshatching, stippling
    weight: consistent pen width, varied density
    color: black ink
    texture: clean ink lines on paper
    edgeTreatment: sharp, precise ink edges
  lighting:
    type: created through line density and crosshatching
    direction: indicated by line direction and density
    intensity: shown through varying line techniques
    shadows:
      style: dense crosshatching or solid ink areas
      color: black ink
      opacity: solid black
    highlights: white paper showing through
  rendering:
    technique: traditional pen and ink techniques
    texture: paper texture showing through ink
    detailLevel: high (precise line control allows fine detail)
    finish: matte ink on paper
  perspective: traditional linear perspective
  mood:
    overall: precise, classic, detailed
    emotion: craftsmanship, concentration, timeless
    tempo: deliberate, careful
    keywords:
    - precise
    - classic
    - detailed
    - timeless
    - meticulous
  stylePrecedents:
  - Aubrey Beardsley illustrations
  - architectural technical drawings