styleName: Pencil Sketch Style
description: Traditional pencil drawing aesthetic with organic lines, crosshatching, stippling, and graphite textures. Features blending techniques and paper tooth interaction.
aiPrompts:
  basePrompt: pencil sketch, graphite drawing, crosshatching, stippling, hand-drawn, blending stumps, tortillion, eraser highlights
  negativePrompt: color, digital art, photo, painting, smooth gradients
  styleKeywords:
  - pencil
  - sketch
  - graphite
  - crosshatch
  - stippling
  - blending
  - hand-drawn
  - traditional art
visualElements:
  colorPalette:
    primary:
    - '#2B2B2B'
    - '#4A4A4A'
    - '#6B6B6B'
    - '#8C8C8C'
    - '#ADADAD'
    - '#CECECE'
    - '#F0F0F0'
    secondary:
    - '#FFFFFF'
    - '#1A1A1A'
    background: white or off-white paper
    usageNotes: Monochromatic grayscale only. Use varying shades for depth
    saturation: none
    contrast: medium to high
  lineArt:
    style: organic, hand-drawn
    weight: variable (0.5-3px)
    color: grayscale
    texture: rough, sketchy with visible breaks, paper tooth interaction
    edgeTreatment: natural variations, multiple overlapping strokes, line spacing affects value density
  lighting:
    type: traditional shading
    direction: typically top-left
    intensity: varies with pressure
    shadows:
      style: crosshatching, stippling, and scribbling
      color: darker graphite tones with reflective shine
      opacity: built up through layering and line density
    highlights: paper showing through, eraser lifting, blending stump work
  rendering:
    technique: traditional pencil on paper with blending tools
    texture: visible paper grain and tooth, graphite-paper interaction
    detailLevel: varies from loose to highly detailed
    finish: intentionally incomplete with visible process and graphite shine
  perspective: traditional drawing perspectives
  mood:
    overall: artistic, unfinished, spontaneous
    emotion: raw, authentic, contemplative
    tempo: calm, thoughtful
    keywords:
    - artistic
    - raw
    - authentic
    - traditional
    - sketchy
  postProcessing:
    effects:
    - paper texture
    - graphite smudging
    - reflective graphite shine
    filters: none
    adjustments:
      saturation: '0'
      contrast: natural pencil contrast
  stylePrecedents:
  - Academic drawing studies
  - 19th century graphite sketches
  - Contemporary pencil portraiture