styleName: Persian Miniature Style
description: Intricate Persian miniature aesthetic with rich colors, elaborate patterns, and flat perspective storytelling scenes
aiPrompts:
  basePrompt: Persian miniature illustration, fine detail, ornate patterns, rich colors, flat perspective, Islamic art
  negativePrompt: photorealistic, modern shading, deep perspective, minimalist
  styleKeywords:
  - Persian miniature
  - ornate
  - flat perspective
  - detailed
  - historic
visualElements:
  colorPalette:
    primary:
    - lapis blue
    - rich gold
    - crimson
    - jade green
    secondary:
    - turquoise
    - ivory
    - burnt orange
    background: aged paper with gold accents
    usageNotes: Rich natural pigments with gold leaf details
    saturation: high
    contrast: medium
  lineArt:
    style: fine ink outlines around figures and patterns
    weight: thin, delicate
    color: dark brown or black (with gold highlights)
    texture: smooth, flowing
    edgeTreatment: crisp, organic curves
  lighting:
    type: flat (decorative, non-realistic)
    direction: none (stylized)
    intensity: even
    shadows:
      style: minimal or decorative patterns
      color: deeper tones of base colors
      opacity: light
    highlights: gold leaf shine
  rendering:
    technique: hand-painted miniature on paper
    texture: smooth with fine brush strokes
    detailLevel: very high (elaborate details and patterns)
    finish: matte with metallic gold accents
  perspective: stacked, flattened perspective
  mood:
    overall: elegant, narrative, cultural
    emotion: scholarly beauty, nostalgia
    tempo: calm and detailed
    keywords:
    - ornate
    - historical
    - narrative
    - delicate
    - rich
  stylePrecedents:
  - Shahnameh miniature paintings
  - Kamal ud-Din Behzad (Persian court artist)