styleName: Pop Art Style
description: 1960s art movement inspired by mass culture and consumerism, featuring bright colors, repetition, commercial imagery, and ironic commentary
aiPrompts:
  basePrompt: pop art, mass culture imagery, bright colors, screen printing, commercial style, repetition, consumer products
  negativePrompt: fine art tradition, muted colors, unique composition, handcrafted appearance, elitist themes
  styleKeywords:
  - pop art
  - mass culture
  - bright colors
  - commercial
  - repetition
visualElements:
  colorPalette:
    primary:
    - hot pink
    - electric blue
    - bright yellow
    secondary:
    - orange
    - green
    - red
    background: bold colored backgrounds or commercial settings
    usageNotes: Bright, commercial colors like advertising
    saturation: very high (bold, attention-grabbing)
    contrast: high (bold commercial appeal)
  lineArt:
    style: bold, commercial-style outlines
    weight: consistent, screen-print quality
    color: black or bold color outlines
    texture: flat, commercial printing quality
    edgeTreatment: sharp, clean commercial edges
  lighting:
    type: flat, commercial lighting
    direction: even, advertising-style lighting
    intensity: bright, attention-grabbing
    shadows:
      style: simple, graphic shadows
      color: solid colors
      opacity: flat, commercial
    highlights: bold, graphic highlights
  rendering:
    technique: screen printing or commercial reproduction
    texture: flat, printed texture
    detailLevel: simplified for mass reproduction
    finish: flat, commercial print finish
  perspective: simple, commercial perspective
  mood:
    overall: bold, commercial, ironic
    emotion: celebration and critique of consumer culture
    tempo: energetic, commercial
    keywords:
    - bold
    - commercial
    - ironic
    - consumer-focused
    - mass-produced
  stylePrecedents:
  - Andy Warhol soup cans
  - Roy Lichtenstein comic strips