styleName: Pre-Raphaelite Brotherhood Style
description: A mid-19th century English movement that rejected the academic conventions of the time for the intense color, high detail, and complex compositions of early Italian Renaissance art (before Raphael).
aiPrompts:
  basePrompt: pre-raphaelite painting, intense colors, high detail, medieval themes, literary subjects, symbolic, John Everett Millais style
  negativePrompt: sfumato, dark shadows, loose brushwork, modern, abstract, minimalist
  styleKeywords:
  - pre-raphaelite
  - detailed
  - vibrant
  - literary
  - medievalism
  - symbolic
visualElements:
  colorPalette:
    primary:
    - jewel-like reds
    - vibrant greens
    - deep blues
    - rich purples
    secondary:
    - gold
    - ivory
    - orange
    background: highly detailed natural or interior settings
    usageNotes: Luminous, saturated colors applied over a wet white ground to enhance brightness.
    saturation: very high
    contrast: high, due to sharp details and bright colors
  lineArt:
    style: sharp, clear, and precise outlines
    weight: thin and controlled
    color: often integrated, but forms are clearly delineated
    texture: smooth application of paint
    edgeTreatment: crisp, sharp edges
  lighting:
    type: bright, even, almost shadowless lighting
    direction: often frontal, illuminating every detail clearly
    intensity: high and clear
    shadows:
      style: minimal and detailed, not broad or dark
      color: colored with local tones, not black
      opacity: light
    highlights: sharp and precise
  rendering:
    technique: meticulous oil painting with fine brushes, "truth to nature"
    texture: extreme attention to the texture of fabrics, hair, and foliage
    detailLevel: extremely high, every part of the canvas is detailed
    finish: smooth, enamel-like surface
  perspective: sometimes flattened or unconventional to fit complex compositions
  mood:
    overall: romantic, symbolic, earnest
    emotion: melancholy, love, tragedy, spirituality
    tempo: static, contemplative
    keywords:
    - detailed
    - luminous
    - symbolic
    - romantic
    - medieval
  stylePrecedents:
  - John Everett Millais
  - Dante Gabriel Rossetti
  - William Holman Hunt