styleName: Precisionism Style
description: A modern art movement in the United States from 1915-1940s, peaking in the 1920s-1930s, characterized by precise, sharply defined, geometric forms. Subjects were often unpeopled industrial and urban landscapes like skyscrapers, bridges, and factories, depicted with smooth, clean surfaces and influenced by photography.
aiPrompts:
  basePrompt: Precisionism painting, industrial landscape, geometric forms, clean lines, American modernism, urban architecture, machine age aesthetic, unpeopled industrial scene
  negativePrompt: impressionism, loose brushwork, pastoral scene, organic shapes, chaos
  styleKeywords:
  - Precisionism
  - industrial
  - geometric
  - clean
  - American modernism
  - machine age
  - unpeopled
visualElements:
  colorPalette:
    primary:
    - industrial grays
    - brick reds
    - deep blues
    - black
    secondary:
    - muted ochre
    - off-white
    - metallic silver
    background: clear or stylized sky, abstract geometric planes
    usageNotes: A sober, industrial palette with strong tonal contrasts.
    saturation: low to medium
    contrast: high, emphasizing geometric forms
  lineArt:
    style: sharp, clean, and precise lines that define geometric planes
    weight: thin to medium, very controlled
    color: often dark outlines or defined by sharp color edges
    texture: perfectly smooth
    edgeTreatment: hard, crisp edges
  lighting:
    type: clear, sharp, almost crystalline light
    direction: strong directional light that creates sharp geometric shadows
    intensity: high
    shadows:
      style: sharply defined geometric shapes
      color: dark, solid colors
      opacity: solid
    highlights: clean, sharp highlights on architectural edges
  rendering:
    technique: smooth oil painting with invisible brushstrokes, inspired by photography
    texture: smooth, untextured surfaces of metal and concrete
    detailLevel: moderate, simplified to its geometric essence
    finish: smooth, clean, almost mechanical
  perspective: often uses dramatic angles and multiple viewpoints to emphasize geometry
  mood:
    overall: monumental, orderly, modern
    emotion: awe of industry, admiration for structure and function, a sense of American power
    tempo: static, monumental
    keywords:
    - industrial
    - geometric
    - monumental
    - clean
    - modern
  stylePrecedents:
  - Charles Demuth
  - Charles Sheeler
  - Georgia O'Keeffe
  - George Ault
  - Ralston Crawford
  - Elsie Driggs