styleName: Realism Art Style
description: A mid-19th century movement aiming to represent subjects truthfully, without idealization, often focusing on everyday life, labor, and social issues of the common people.
aiPrompts:
  basePrompt: realism painting, everyday life, social commentary, unidealized figures, 19th century, Gustave Courbet style, genre painting
  negativePrompt: idealized, mythological, abstract, romanticized, fantasy, heroic
  styleKeywords:
  - realism
  - everyday
  - social
  - unidealized
  - objective
  - truthful
visualElements:
  colorPalette:
    primary:
    - earthy browns
    - muted grays
    - somber greens
    secondary:
    - stone colors
    - worn fabric tones
    - dull blues
    background: ordinary interiors, rural landscapes, urban settings
    usageNotes: A sober, naturalistic palette reflecting the reality of the subject.
    saturation: low to medium
    contrast: natural, often reflecting harsh or plain lighting
  lineArt:
    style: naturalistic contours defined by form and light, not strong outlines
    weight: n/a
    color: integrated into the form
    texture: realistic depiction of textures (wood, stone, cloth)
    edgeTreatment: realistic, unidealized edges
  lighting:
    type: natural and often stark or unflattering light
    direction: as it would appear in reality, without dramatic effect
    intensity: moderate, realistic
    shadows:
      style: rendered truthfully from the light source
      color: dark, neutral tones
      opacity: realistic
    highlights: natural reflections, not idealized
  rendering:
    technique: meticulous oil painting to capture details accurately
    texture: faithful reproduction of real-world textures
    detailLevel: high, focused on truthful representation
    finish: matte, non-glamorous
  perspective: accurate linear and atmospheric perspective
  mood:
    overall: objective, sober, observant
    emotion: empathy, dignity in labor, social awareness
    tempo: static, a captured moment of reality
    keywords:
    - objective
    - truthful
    - everyday
    - unembellished
    - social
  stylePrecedents:
  - Gustave Courbet
  - Jean-François Millet
  - Honoré Daumier