styleName: Renaissance Art Style
description: A European art style from the 14th to the 16th century, characterized by a return to classical ideals of beauty, harmony, and realism. It emphasizes linear perspective, the study of anatomy, soft chiaroscuro (sfumato), and both religious and mythological themes.
aiPrompts:
  basePrompt: renaissance painting, classical harmony, sfumato, realistic anatomy, biblical scene, mythological figures, oil on canvas
  negativePrompt: abstract, modern art, distorted, flat perspective, pixelated, chaotic
  styleKeywords:
  - renaissance
  - classical
  - sfumato
  - chiaroscuro
  - realism
  - harmony
visualElements:
  colorPalette:
    primary:
    - deep reds (carmine)
    - ultramarine blue
    - rich golds
    - earthy browns
    secondary:
    - flesh tones
    - olive green
    - ivory white
    background: architectural interiors, idealized landscapes
    usageNotes: A rich, harmonious color palette with subtle tonal transitions.
    saturation: medium to high, natural
    contrast: medium, built through light and shadow
  lineArt:
    style: soft, fluid contours, often blurred by the sfumato technique
    weight: varied, natural
    color: integrated into the painting, rarely as a black outline
    texture: smooth, realistic transitions
    edgeTreatment: soft, blurred edges (sfumato)
  lighting:
    type: soft, directional chiaroscuro
    direction: usually from a single source, creating depth
    intensity: moderate, realistic
    shadows:
      style: deep but soft, with subtle transitions
      color: warm browns and umber
      opacity: translucent, built up in layers
    highlights: delicate, emphasizing form
  rendering:
    technique: oil painting, tempera, fresco, with attention to detail
    texture: smooth surface with invisible brushstrokes
    detailLevel: very high (anatomy, fabrics, architecture)
    finish: smooth, with a subtle sheen of oil paint
  perspective: precise linear and atmospheric perspective
  mood:
    overall: harmonious, sublime, intellectual
    emotion: serenity, divinity, humanism, dignity
    tempo: calm, static, timeless
    keywords:
    - harmonious
    - sublime
    - realistic
    - classical
    - divine
  stylePrecedents:
  - Leonardo da Vinci
  - Raphael
  - Michelangelo
  - Titian