styleName: Retro Pixel Art Style
description: Classic pixel art aesthetic with limited colors, hard edges, and nostalgic 8-bit/16-bit game visuals
aiPrompts:
  basePrompt: pixel art, retro game style, 8-bit, 16-bit, pixelated
  negativePrompt: smooth, anti-aliased, gradients, photorealistic, blurry
  styleKeywords:
  - pixel art
  - retro
  - 8-bit
  - 16-bit
  - blocky
  - pixelated
visualElements:
  colorPalette:
    primary:
    - system-specific limited palette
    - dithering for color mixing
    secondary:
    - high contrast combinations
    - pure saturated colors
    background: solid colors from limited palette
    usageNotes: Strict palette limitations per gaming system, dithering patterns for transitions
    saturation: high
    contrast: maximum
  lineArt:
    style: pixel-perfect outlines
    weight: 1 pixel
    color: dark palette color
    texture: hard edges
    edgeTreatment: no anti-aliasing
  lighting:
    type: flat or simple cell shading
    direction: varies by game design
    intensity: limited value steps
    shadows:
      style: dithering patterns
      color: darker palette color
      opacity: solid
    highlights: lighter palette color
  rendering:
    technique: pixel placement
    texture: dithering patterns
    detailLevel: minimal, iconic
    finish: crisp pixels
  perspective: isometric, side-scrolling, or orthographic
  mood:
    overall: nostalgic, playful, retro
    emotion: fun, energetic, classic gaming
    tempo: rhythmic, game-like pacing
    keywords:
    - nostalgic
    - retro
    - gaming
    - 8-bit
    - classic
  postProcessing:
    effects:
    - pixelation
    - color reduction
    - CRT scanline simulation
    filters: nearest neighbor scaling
    adjustments:
      saturation: high
      contrast: maximum
      sharpness: crisp pixel edges
  stylePrecedents:
  - Nintendo 8-bit graphics
  - Atari 2600 game sprites
  - Game Boy monochrome graphics
  - 16-bit console artwork