styleName: Risograph Print Style
description: Japanese stencil-based duplicator printing technique from the 1980s with distinctive grain texture, limited spot colors (2-4 maximum), overprint effects, and intentionally imperfect registration creating a handmade aesthetic popular in indie zine culture
aiPrompts:
  basePrompt: risograph print style, stencil printing, grain texture, limited spot colors, overprint effect, misregistration, textured, soy-based ink
  negativePrompt: smooth, photorealistic, digital, many colors, perfect registration, clean gradients, offset printing
  styleKeywords:
  - risograph
  - grain
  - overprint
  - textured
  - limited palette
  - spot color
visualElements:
  colorPalette:
    primary:
    - bright pink
    - fluorescent blue
    - yellow
    - red
    secondary:
    - teal
    - orange
    - purple
    background: off-white paper
    usageNotes: Maximum 3-4 colors, overlapping creates new colors
    saturation: very high - fluorescent
    contrast: high
  lineArt:
    style: bold, simple shapes
    weight: medium to thick
    color: spot color ink
    texture: grainy, textured
    edgeTreatment: slightly imperfect registration
  lighting:
    type: flat color layers
    direction: n/a
    intensity: bright spot colors
    shadows:
      style: created by color overlap
      color: mixed from overlapping inks
      opacity: multiply blend
    highlights: paper showing through
  rendering:
    technique: layered spot color printing
    texture: heavy grain, paper texture visible
    detailLevel: simplified for print process
    finish: imperfect registration, grain texture
  perspective: flat, graphic design approach
  mood:
    overall: playful, retro, handmade
    emotion: energetic, creative, indie
    tempo: vibrant, dynamic
    keywords:
    - indie
    - creative
    - handmade
    - vibrant
    - experimental
  stylePrecedents:
  - Independent zine publishing
  - RISO printing technique