styleName: Rococo Style
description: 18th-century French decorative art style featuring lightness, elegance, pastel colors, ornate decoration, and aristocratic leisure scenes
aiPrompts:
  basePrompt: rococo painting, elegant decoration, pastel colors, aristocratic scenes, ornate details, french salon, delicate beauty
  negativePrompt: dark colors, heavy forms, religious themes, stark simplicity, industrial themes
  styleKeywords:
  - rococo
  - elegant
  - pastel colors
  - ornate decoration
  - aristocratic
visualElements:
  colorPalette:
    primary:
    - pale pink
    - powder blue
    - cream white
    secondary:
    - gold leaf
    - soft lavender
    - mint green
    background: elegant interior settings or pastoral landscapes
    usageNotes: Soft, refined pastel colors with gold accents
    saturation: low to medium (delicate, refined)
    contrast: low (soft, harmonious)
  lineArt:
    style: delicate, flowing curves
    weight: light, graceful lines
    color: soft, subtle outlines
    texture: smooth, refined finish
    edgeTreatment: soft, curved edges
  lighting:
    type: soft, diffused lighting
    direction: gentle, flattering illumination
    intensity: soft, never harsh
    shadows:
      style: soft, delicate shadows
      color: light grays and pastels
      opacity: very light
    highlights: gentle, pearlescent highlights
  rendering:
    technique: smooth oil painting with fine detail
    texture: silk, porcelain, delicate fabrics
    detailLevel: high (ornate decorative details)
    finish: smooth, polished finish
  perspective: intimate, human scale
  mood:
    overall: elegant, refined, leisurely
    emotion: pleasure, refinement, grace
    tempo: leisurely, graceful
    keywords:
    - elegant
    - refined
    - graceful
    - delicate
    - aristocratic
  stylePrecedents:
  - Antoine Watteau paintings
  - François Boucher court scenes
  - Fragonard romantic scenes