styleName: Romanticism Art Style
description: An artistic movement from the turn of the 18th and 19th centuries, emphasizing emotion, individualism, mystery, and the power of nature. Works are characterized by drama, dynamic composition, and a subjective, often melancholic or heroic approach.
aiPrompts:
  basePrompt: romanticism painting, dramatic landscape, sublime nature, emotional intensity, stormy sea, ancient ruins, heroic figure
  negativePrompt: calm, static, geometric, minimalist, photorealistic, objective
  styleKeywords:
  - romanticism
  - dramatic
  - sublime
  - emotional
  - nature
  - heroic
visualElements:
  colorPalette:
    primary:
    - deep blues
    - stormy grays
    - fiery reds and oranges (sunsets)
    secondary:
    - earthy browns
    - forest greens
    - golden light
    background: dramatic skies, powerful mountains, stormy seas
    usageNotes: A contrasting color palette that emphasizes the drama of the scene.
    saturation: medium to high
    contrast: high, dramatic
  lineArt:
    style: expressive, painterly, often indistinct
    weight: dynamic, varied
    color: integrated with the color patch
    texture: visible brushstrokes, impasto
    edgeTreatment: soft, atmospheric edges
  lighting:
    type: dramatic, theatrical, often from an unseen source
    direction: diagonal, breaking through clouds, moonlight
    intensity: strong contrasts of light and shadow
    shadows:
      style: deep, vast, building a mood of mystery
      color: dark browns, blues, violets
      opacity: heavy, blurred
    highlights: intense, often on the central point of the composition
  rendering:
    technique: oil painting, free brushstrokes
    texture: distinct paint texture, impastos
    detailLevel: varied - from detailed figures to sketchy backgrounds
    finish: painterly, expressive
  perspective: deep atmospheric perspective, often with a monumental foreground
  mood:
    overall: dramatic, emotional, sublime
    emotion: terror, awe, melancholy, longing, heroism
    tempo: dynamic, turbulent
    keywords:
    - emotional
    - sublime
    - dramatic
    - mysterious
    - powerful
  stylePrecedents:
  - Caspar David Friedrich
  - J.M.W. Turner
  - Théodore Géricault
  - Francisco Goya