styleName: Romanticism Art Style
description: Dramatic artistic style emphasizing emotion, individualism, sublime nature, and passionate expression with turbulent landscapes and heroic figures
aiPrompts:
  basePrompt: romanticism painting, dramatic landscape, sublime nature, emotional intensity, stormy atmosphere, heroic figure, turbulent skies, wild nature, passionate expression
  negativePrompt: calm scenes, static composition, geometric patterns, minimalist, photorealistic, objective documentation, peaceful atmosphere, rational approach
  styleKeywords:
  - romanticism
  - dramatic
  - sublime
  - emotional
  - turbulent
  - heroic
  - passionate
visualElements:
  colorPalette:
    primary:
    - deep stormy blue
    - dramatic gray
    - fiery orange
    secondary:
    - rich brown earth
    - forest green
    - golden sunlight
    background: turbulent skies, sublime mountains, stormy seas
    usageNotes: Contrasting dramatic colors emphasizing emotional intensity
    saturation: medium to high (emotional impact)
    contrast: high (dramatic light and shadow)
  lineArt:
    style: expressive, painterly, atmospheric
    weight: dynamic, varied brushwork
    color: integrated with color masses
    texture: visible brush strokes, impasto technique
    edgeTreatment: soft, atmospheric edges
  lighting:
    type: dramatic, theatrical, supernatural
    direction: diagonal rays, moonlight, storm lighting
    intensity: strong contrasts between light and shadow
    shadows:
      style: deep, mysterious, mood-building
      color: rich dark blues, purples, browns
      opacity: heavy, atmospheric
    highlights: intense, focused on dramatic elements
  rendering:
    technique: oil painting, expressive brushwork
    texture: visible paint texture, impasto effects
    detailLevel: varied (detailed foreground, atmospheric background)
    finish: painterly, expressive surface
  perspective: atmospheric perspective with monumental scale
  mood:
    overall: dramatic, sublime, emotionally intense
    emotion: awe, terror, melancholy, heroic passion
    tempo: dynamic, turbulent, passionate
    keywords:
    - sublime
    - dramatic
    - emotional
    - mysterious
    - heroic
  stylePrecedents:
  - Caspar David Friedrich wanderer paintings
  - J.M.W. Turner storm seascapes
  - Theodore Gericault Raft of Medusa
  - Francisco Goya dark paintings