styleName: Scratchboard Style
description: Scratch art technique where black ink is scratched away from a prepared board to reveal white or colored layers underneath
aiPrompts:
  basePrompt: scratchboard art, scratch technique, white lines on black, engraving style, scraped surface
  negativePrompt: painted, drawn with pen, smooth gradients, color painting, photographic
  styleKeywords:
  - scratchboard
  - scratch art
  - engraving
  - scraped
  - white on black
visualElements:
  colorPalette:
    primary:
    - black surface
    - white scratches
    - single color layer
    secondary:
    - gray tones (partial scratching)
    - earth tones (colored boards)
    background: black scratchboard surface
    usageNotes: High contrast between black surface and scratched areas
    saturation: low (mostly black and white)
    contrast: very high (black background, white lines)
  lineArt:
    style: scratched lines revealing underlying color
    weight: varies by scratching tool and pressure
    color: white or underlying board color
    texture: rough, scratched texture
    edgeTreatment: rough, hand-scratched edges
  lighting:
    type: created by scratching density and direction
    direction: indicated by scratch direction
    intensity: controlled by amount of scratching
    shadows:
      style: areas left unscratched (solid black)
      color: black board surface
      opacity: solid
    highlights: heavily scratched areas showing maximum underlying color
  rendering:
    technique: physical scratching away of black surface
    texture: rough scratched texture, tool marks visible
    detailLevel: high (precise scratch control)
    finish: matte, textured surface
  perspective: traditional perspective through scratched lines
  mood:
    overall: dramatic, high contrast, crafted
    emotion: intensity, craftsmanship, boldness
    tempo: deliberate, careful
    keywords:
    - dramatic
    - high contrast
    - intense
    - crafted
    - bold
  stylePrecedents:
  - traditional engraving techniques
  - M.C. Escher woodcut style