styleName: Skeuomorphism Style
description: Digital interface design style where elements mimic real-world counterparts to help users transition from physical to digital interfaces. Dominant in early iOS (2007-2013) before iOS 7 flat design revolution. Features rich textures, shadows, and realistic materials.
aiPrompts:
  basePrompt: skeuomorphic UI design, realistic interface, leather texture, brushed metal, drop shadows, physical object metaphor, early iOS style, textured buttons, realistic materials
  negativePrompt: flat design, minimalist, abstract, material design, no textures, modern iOS, geometric shapes
  styleKeywords:
  - skeuomorphism
  - realistic UI
  - textured interface
  - 3D interface elements
  - analog metaphor
  - iOS pre-2013
  - tactile design
visualElements:
  colorPalette:
    primary:
    - leather shades (browns)
    - metallic grays
    - wood colors
    secondary:
    - green felt color (gaming tables)
    - yellow paper color (notepads)
    - blue denim texture
    background: textured backgrounds (linen binding, metal plate, felt surface)
    usageNotes: Colors and materials directly mimic physical objects
    saturation: natural, muted
    contrast: medium, built through shadows and lights
  lineArt:
    style: none, edges defined by shadows, lights and seams
    weight: n/a
    color: n/a
    texture: visible seams on leather, edges of metal plates, paper grain
    edgeTreatment: rounded, physical edges with beveling
  lighting:
    type: realistic, studio lighting
    direction: usually from above, at slight angle (top-down)
    intensity: moderate, creating subtle shadows
    shadows:
      style: soft drop shadows and inner shadows
      color: dark gray or black
      opacity: light to medium, blurred
    highlights: subtle gradients and reflections on shiny surfaces
  rendering:
    technique: photorealistic material rendering
    texture: leather, metal, wood, paper, glass, felt, denim
    detailLevel: very high, with attention to details like seams, stitching, grain
    finish: varied depending on material (matte leather, shiny metal, textured paper)
  perspective: flat interface with strong illusion of depth and physicality
  mood:
    overall: familiar, tactile, rich
    emotion: comfort, nostalgia for analog world, satisfaction with details
    tempo: static, solid
    keywords:
    - tactile
    - realistic
    - rich
    - familiar
    - analog
    - nostalgic
  stylePrecedents:
  - iOS 6 Calendar app (stitched leather texture)
  - iOS Notes app (yellow lined paper with torn edge)
  - iOS Voice Memos (realistic microphone interface)
  - iOS Newsstand (wooden bookshelf)
  - GarageBand interface (realistic instrument controls)
  - iBooks interface (wooden bookshelf, page turning)
  - early macOS Address Book (leather-bound contact book)
  - iOS Contacts (leather binding with metal corners)