styleName: Socialist Realism Style
description: Official art style of the Soviet Union and other Eastern Bloc countries, aimed at glorifying communist ideals, work, leaders, and working people. The style is monumental, propagandistic, and seemingly realistic but actually idealized.
aiPrompts:
  basePrompt: socialist realism painting, soviet propaganda art, monumental figures, glorifying labor, heroic workers, communist leaders, optimistic scene
  negativePrompt: abstract, modernism, surrealism, dark, pessimistic, critical, formal experimentation
  styleKeywords:
  - socialist realism
  - socrealism
  - soviet art
  - propaganda
  - heroic
  - monumental
visualElements:
  colorPalette:
    primary:
    - banner red
    - sunny yellow
    - sky blue
    - white
    secondary:
    - earth colors (browns, greens)
    - skin tones
    - machinery grays
    background: factories, fields, construction sites, bright sky
    usageNotes: Palette is bright, optimistic and full of sunshine. Red is key symbolic color.
    saturation: high, vivid
    contrast: medium to high, but without dark, dramatic shadows
  lineArt:
    style: strong, academic drawing, clear contours
    weight: confident, decisive
    color: integrated with form
    texture: smooth, clean
    edgeTreatment: clear, sculptural edges
  lighting:
    type: bright, sunny, optimistic light
    direction: usually from above, illuminating scene evenly
    intensity: high, almost shadowless
    shadows:
      style: minimized, soft
      color: natural, never black
      opacity: light
    highlights: bright, emphasizing health and strength of figures
  rendering:
    technique: academic oil painting, smooth, without visible brushstrokes
    texture: realistic but idealized textures (e.g., clean work clothes)
    detailLevel: high, with attention to machinery and portrait details
    finish: smooth, polished
  perspective: classical, monumental, often from low viewpoint to elevate figures
  mood:
    overall: heroic, optimistic, propagandistic
    emotion: pride, work enthusiasm, faith in future, strength
    tempo: dynamic, march-like
    keywords:
    - propagandistic
    - heroic
    - optimistic
    - monumental
    - ideological
  stylePrecedents:
  - Aleksandr Deyneka
  - Isaak Brodsky
  - Vera Mukhina (sculpture)