styleName: Solarized Silhouette Style
description: High-contrast silhouettes with solarization effects, featuring tone reversal, bright line outlines, and eerie metallic appearance
aiPrompts:
  basePrompt: solarized silhouette, Sabattier effect, tone reversal, bright line outlines, eerie silver tones, high contrast, metallic appearance, grain texture, partial tone inversion
  negativePrompt: normal tone mapping, standard contrast, smooth gradients, clean edges, realistic colors, detailed features, internal details
  styleKeywords:
  - solarized
  - Sabattier effect
  - tone reversal
  - bright line outlines
  - silhouette
  - high contrast
  - metallic tones
  - grain texture
  - eerie silver
visualElements:
  colorPalette:
    primary:
    - eerie silver
    - metallic white
    - deep black
    - bright white outlines
    secondary:
    - gunmetal gray
    - pewter
    - pure black silhouette
    background: tone-reversed gradient with bright line separations
    usageNotes: Metallic and silver tones with bright outline separations
    saturation: low to medium with metallic sheen
    contrast: extreme high contrast with tone reversal
  lineArt:
    style: bright line outlines at tone boundaries
    weight: thin bright lines separating tonal areas
    color: bright white or silver
    texture: sharp bright outlines with metallic appearance
    edgeTreatment: distinctive bright line separation between tones
  lighting:
    type: tone-reversed lighting with bright outlines
    direction: creates characteristic solarization boundaries
    intensity: tone reversal in mid-tones and highlights
    shadows:
      style: partially inverted tones
      color: mixed dark and light due to reversal
      opacity: varies due to solarization effect
    highlights: bright line outlines at tonal boundaries
  rendering:
    technique: solarization tone reversal with bright line formation
    texture: grain overlay with metallic appearance
    detailLevel: silhouette with bright outline definition
    finish: eerie silver film effect with tone inversion
  perspective: varies - focus on strong tonal contrast and bright outlines
  mood:
    overall: eerie, dramatic, otherworldly
    emotion: mysterious, striking, unsettling
    tempo: dramatic tension
    keywords:
    - eerie
    - dramatic
    - otherworldly
    - mysterious
    - metallic
  stylePrecedents:
  - Man Ray solarized photographs
  - Sabattier effect darkroom techniques
  - experimental film photography
  - avant-garde photo manipulation