styleName: Solarpunk Style
description: Optimistic eco-futuristic utopia where technology and nature coexist in harmony with sustainable design
aiPrompts:
  basePrompt: solarpunk utopian city, futuristic architecture integrated with nature, vertical forests, solar panels, lush greenery, flowing organic lines, bright sunlight, art nouveau influence, sustainable technology
  negativePrompt: dystopian, polluted, industrial, dark, gritty, cyberpunk, concrete jungle
  styleKeywords:
  - solarpunk
  - utopian
  - eco-futurism
  - sustainable
  - harmony with nature
  - biophilic design
  - Art Nouveau
visualElements:
  colorPalette:
    primary:
    - vibrant green
    - sky blue
    - golden yellow
    - clean white
    secondary:
    - warm orange
    - natural wood brown
    - soft lavender
    background: bright blue sky with white clouds
    usageNotes: Bright, optimistic colors inspired by nature and sunlight
    saturation: medium to high
    contrast: moderate
  lineArt:
    style: flowing organic curves inspired by Art Nouveau
    weight: medium, elegant
    color: natural greens and browns
    texture: smooth, botanical
    edgeTreatment: soft, organic transitions
  lighting:
    type: abundant natural sunlight
    direction: golden hour lighting
    intensity: bright and warm
    shadows:
      style: soft, dappled through foliage
      color: cool blue-green
      opacity: light
    highlights: sun glints on solar panels and glass
  rendering:
    technique: clean digital painting with organic details
    texture: natural materials, living plants, smooth tech
    detailLevel: high in botanical elements
    finish: fresh, clean, luminous
  perspective: wide panoramic views showing city-nature integration
  mood:
    overall: hopeful, harmonious, peaceful
    emotion: optimism, community, wonder
    tempo: calm, flowing
    keywords:
    - optimistic
    - sustainable
    - harmonious
    - verdant
    - innovative
  stylePrecedents:
  - Vincent Callebaut architecture
  - Studio Ghibli nature scenes
  - Art Nouveau botanical designs