styleName: Steampunk Clockwork Style
description: Victorian steampunk aesthetic with brass clockwork gears, ornate Victorian design elements, and a muted industrial color palette
aiPrompts:
  basePrompt: steampunk illustration, brass gears, Victorian ornamentation, steam machinery, sepia tone
  negativePrompt: sleek modern tech, plastic materials, neon colors, minimalism
  styleKeywords:
  - steampunk
  - clockwork
  - Victorian
  - brass
  - industrial
visualElements:
  colorPalette:
    primary:
    - brass
    - copper
    - sepia brown
    - dark bronze
    secondary:
    - black iron
    - antique gold
    - parchment beige
    background: aged parchment or smoky gray backdrop
    usageNotes: Warm metallic tones with patina and soot accents
    saturation: low to medium (antique muted quality)
    contrast: medium
  lineArt:
    style: engraved ornate linework
    weight: medium (with decorative flourishes)
    color: dark brown or black
    texture: slightly rough, etched lines
    edgeTreatment: Victorian scrollwork and gear teeth details
  lighting:
    type: dramatic sepia glow
    direction: soft spotlight or diffused through steam
    intensity: moderate (dim, antique lighting)
    shadows:
      style: soft gear and gadget shadows
      color: brown-gray
      opacity: medium
    highlights: warm glow on metal surfaces (gaslight effect)
  rendering:
    technique: textured digital painting with grunge overlays
    texture: grime, rust, and scratches on surfaces
    detailLevel: high (many gears, gauges, filigree)
    finish: matte base with metallic gleams
  perspective: mix of mechanical diagram elements and scenic views (e.g., cutaways)
  mood:
    overall: inventive, nostalgic, mechanical
    emotion: wonder, industriousness
    tempo: steady tick-tock
    keywords:
    - Victorian
    - mechanical
    - ornate
    - nostalgic
    - adventurous
  stylePrecedents:
  - Jules Verne illustration aesthetics
  - classic steampunk concept art