styleName: Steampunk Style
description: Victorian-era retrofuturism featuring steam-powered machinery, brass and copper mechanisms, and elaborate mechanical designs
aiPrompts:
  basePrompt: steampunk art, Victorian machinery, brass gears, steam engines, copper pipes, mechanical clockwork, airships
  negativePrompt: modern technology, plastic, digital, minimalist, contemporary
  styleKeywords:
  - steampunk
  - Victorian
  - brass
  - mechanical
  - industrial
visualElements:
  colorPalette:
    primary:
    - brass
    - copper
    - dark bronze
    - rich brown
    secondary:
    - deep burgundy
    - forest green
    - antique gold
    background: Victorian interiors or industrial settings
    usageNotes: Warm metallic tones with rich Victorian colors
    saturation: medium
    contrast: medium to high
  lineArt:
    style: intricate mechanical details
    weight: varied, detailed linework
    color: dark brown or black
    texture: etched, engraved quality
    edgeTreatment: ornate Victorian flourishes
  lighting:
    type: gaslight ambiance or workshop lighting
    direction: warm directional light
    intensity: moody, atmospheric
    shadows:
      style: deep Victorian shadows
      color: warm brown
      opacity: heavy
    highlights: brass reflections, steam glow
  rendering:
    technique: detailed illustration or digital painting
    texture: metal patina, leather, wood grain
    detailLevel: very high (gears, pipes, rivets)
    finish: aged metals, polished brass accents
  perspective: often cutaway or exploded views
  mood:
    overall: adventurous, mysterious, mechanical
    emotion: curiosity, invention, nostalgia
    tempo: steady, mechanical rhythm
    keywords:
    - mechanical
    - Victorian
    - adventurous
    - ornate
    - industrial
  stylePrecedents:
  - Jules Verne illustrations
  - The Wild Wild West
  - Victorian engineering drawings