styleName: Stipple Pointillism Style
description: Art created entirely with dots and points using stippling (monochromatic ink dots for tonal values) and pointillism (colored dots for optical color mixing) techniques, building form and tone through dot density and placement
aiPrompts:
  basePrompt: stipple art, pointillism technique, dot artwork, stippling illustration, points only, dot density technique
  negativePrompt: lines, smooth shading, brushstrokes, continuous marks, gradients, washes
  styleKeywords:
  - stipple
  - pointillism
  - dots
  - points
  - stippling
  - dotwork
  - optical mixing
visualElements:
  colorPalette:
    primary:
    - black dots on white
    - single color dots
    secondary:
    - pure color dots for pointillism
    - monochromatic variations for stippling
    background: white or light color
    usageNotes: Tone through dot density, color through optical mixing of pure dots
    saturation: pure colors that mix optically, or monochromatic for stippling
    contrast: created through dot spacing and density variations
  lineArt:
    style: no lines, only dots
    weight: dot size variations from fine to medium
    color: single or multiple pure dot colors
    texture: grainy, textured surface from dots
    edgeTreatment: defined by dot placement and density transitions
  lighting:
    type: implied through dot density variations
    direction: shown through gradual density transitions
    intensity: dot concentration and spacing
    shadows:
      style: dense dot clusters
      color: same as base dots or darker values
      opacity: density based, no transparency
    highlights: sparse dots or empty white space
  rendering:
    technique: methodical dot placement, systematic build-up
    texture: uniform dot texture with varied density
    detailLevel: depends on dot size and placement precision
    finish: textured, optically vibrating surface
  perspective: any perspective, defined by dot patterns and density
  mood:
    overall: meticulous, contemplative, optically dynamic
    emotion: patience, precision, meditation, visual energy
    tempo: slow, methodical, systematic
    keywords:
    - meticulous
    - meditative
    - precise
    - optically vibrating
    - patient
    - systematic
  postProcessing:
    effects:
    - dot texture enhancement
    - optical vibration effect
    - paper texture for traditional stippling
    filters: none (preserves pure dot clarity)
    adjustments:
      saturation: high for pointillism, neutral for stippling
      contrast: high (emphasizes dot definition and spacing)
  stylePrecedents:
  - Giulio Campagnola (stippling pioneer, 1510)
  - Georges Seurat (pointillism)
  - Paul Signac (pointillism)
  - Scientific botanical illustration