styleName: Stipple Pointillism Style
description: Art created entirely with dots and points, building form and tone through dot density
aiPrompts:
  basePrompt: stipple art, pointillism technique, dot artwork, stippling illustration, points only
  negativePrompt: lines, smooth shading, brushstrokes, continuous marks
  styleKeywords:
  - stipple
  - pointillism
  - dots
  - points
  - stippling
  - dotwork
visualElements:
  colorPalette:
    primary:
    - black dots on white
    - single color dots
    secondary:
    - colored dots for pointillism
    background: white or light color
    usageNotes: Tone through dot density, color through optical mixing
    saturation: pure colors that mix optically
    contrast: created through dot spacing
  lineArt:
    style: no lines, only dots
    weight: dot size variations
    color: single or multiple dot colors
    texture: grainy from dots
    edgeTreatment: defined by dot placement
  lighting:
    type: implied through dot density
    direction: shown through gradual transitions
    intensity: dot concentration
    shadows:
      style: dense dot clusters
      color: same as dots
      opacity: density based
    highlights: sparse dots or empty
  rendering:
    technique: methodical dot placement
    texture: uniform dot texture
    detailLevel: depends on dot size and patience
    finish: textured, vibrating surface
  perspective: any, defined by dot patterns
  mood:
    overall: meticulous, contemplative, shimmering
    emotion: patience, precision, meditation
    tempo: slow, methodical
    keywords:
    - meticulous
    - meditative
    - precise
    - shimmering
    - patient
  stylePrecedents:
  - Georges Seurat
  - Paul Signac
  - Scientific illustration
