styleName: Surrealist Dreamlike Style
description: Ethereal, dreamlike imagery exploring the unconscious mind through impossible perspectives, melting forms, automatic drawing techniques, and metaphysical atmosphere with symbolic imagery and psychological significance
aiPrompts:
  basePrompt: surrealist art, dreamlike atmosphere, unconscious mind, automatic drawing, melting forms, impossible perspectives, ethereal, metaphysical, symbolic imagery, Freudian, psychic automatism
  negativePrompt: realistic, logical, harsh lines, geometric, mundane, conventional perspective, rational composition
  styleKeywords:
  - surrealist
  - dreamlike
  - ethereal
  - metaphysical
  - floating
  - impossible
  - unconscious
  - automatic
  - psychic
  - symbolic
  - Freudian
  - juxtaposition
visualElements:
  colorPalette:
    primary:
    - dream blues
    - flesh tones
    - earth browns
    - sunset oranges
    secondary:
    - pale golds
    - dusty roses
    - seafoam greens
    - acidic yellows
    - electric blues
    background: gradient washes, nebulous dreamscapes
    usageNotes: Soft, dreamy colors that blend into each other with both hyper-realistic and unnatural color combinations
    saturation: low to high (varies for dream logic)
    contrast: soft, hazy with dramatic possibilities
  lineArt:
    style: fluid, dissolving, precise realistic detail in impossible contexts
    weight: varied, sometimes fading, fine detail to bold impossible forms
    color: soft, often colored lines, natural or unnatural depending on dream logic
    texture: smooth, organic, hyper-realistic textures in surreal contexts
    edgeTreatment: soft, sometimes undefined, sharp realistic edges creating impossible forms
  lighting:
    type: otherworldly, multiple sources, impossible lighting scenarios
    direction: illogical, dreamlike, multiple impossible light sources
    intensity: soft, glowing, varies dramatically within single image
    shadows:
      style: soft, sometimes defying physics, realistic shadows in impossible situations
      color: colored shadows, natural shadow colors
      opacity: translucent, sometimes impossible
    highlights: ethereal glows, realistic highlights on impossible forms
  rendering:
    technique: smooth blending, sfumato, meticulous realistic technique for unreal subjects
    texture: soft, cloud-like, hyper-realistic textures
    detailLevel: selective focus, some areas sharp, others dissolving, very high for convincing impossible realities
    finish: dreamlike, atmospheric, smooth like oil painting
  perspective: impossible, shifting, non-Euclidean, distorted or multiple impossible perspectives
  mood:
    overall: mysterious, contemplative, otherworldly
    emotion: wonder, unease, transcendence
    tempo: floating, timeless
    keywords:
    - mysterious
    - contemplative
    - otherworldly
    - transcendent
    - impossible
  stylePrecedents:
  - Salvador Dalí melting clocks
  - René Magritte impossible realities
  - Remedios Varo metaphysical landscapes
  - Yves Tanguy biomorphic forms
  - Giorgio de Chirico dreamlike architecture
postProcessing:
  effects:
  - dreamlike blur
  - ethereal glow
  - canvas texture
  - soft focus gradients
  filters: atmospheric processing to enhance otherworldly quality
  adjustments:
    saturation: varies for dream logic
    contrast: soft transitions with selective dramatic areas