styleName: Surrealism Art Style
description: Artistic movement exploring the unconscious mind through dreamlike imagery, impossible combinations, and automatic creative processes
aiPrompts:
  basePrompt: surrealism, dreamlike, impossible combinations, unconscious mind, automatic drawing, bizarre imagery
  negativePrompt: realistic proportions, logical scenes, everyday objects, conventional perspective, rational composition
  styleKeywords:
  - surrealism
  - dreamlike
  - unconscious
  - bizarre
  - impossible
visualElements:
  colorPalette:
    primary:
    - dream blues
    - flesh tones
    - earth browns
    - acidic yellows
    - electric blues
    secondary:
    - sunset oranges
    - deep shadows
    - ethereal whites
    background: dreamlike landscapes or impossible spaces
    usageNotes: Contrast between hyper-realistic and impossible colors, often acidic or electric variations
    saturation: varies (realistic to impossible)
    contrast: high (dramatic light and shadow)
  lineArt:
    style: precise realistic detail in impossible contexts
    weight: varies from fine detail to bold impossible forms
    color: natural or unnatural depending on dream logic
    texture: hyper-realistic textures in surreal contexts
    edgeTreatment: sharp realistic edges creating impossible forms
  lighting:
    type: dramatic, often impossible lighting scenarios
    direction: multiple or impossible light sources
    intensity: varies dramatically within single image
    shadows:
      style: realistic shadows in impossible situations
      color: natural shadow colors
      opacity: varies, sometimes impossible
    highlights: realistic highlights on impossible forms
  rendering:
    technique: meticulous realistic technique for unreal subjects
    texture: hyper-realistic textures
    detailLevel: very high (convincing impossible realities)
    finish: smooth, often oil painting finish
  perspective: often distorted or multiple impossible perspectives
  mood:
    overall: mysterious, unsettling, thought-provoking
    emotion: wonder, unease, fascination
    tempo: static but mentally dynamic
    keywords:
    - mysterious
    - unsettling
    - thought-provoking
    - fascinating
    - impossible
  stylePrecedents:
  - Salvador Dali melting clocks
  - René Magritte impossible realities
  - The Son of Man (Magritte)
  - The Treachery of Images (Magritte)
  - Un Chien Andalou references