styleName: Swiss Style Typography
description: International typographic style emphasizing cleanliness, objectivity, readability with modular grids and sans-serif typography
aiPrompts:
  basePrompt: swiss style typography, clean layout, modular grid, sans-serif fonts, objective design, minimal decoration
  negativePrompt: ornate typography, decorative fonts, chaotic layout, excessive decoration, subjective expression
  styleKeywords:
  - swiss style
  - clean typography
  - modular grid
  - sans-serif
  - objective
visualElements:
  colorPalette:
    primary:
    - black
    - white
    - single accent color
    secondary:
    - gray tones
    - minimal color palette
    - functional colors
    background: white or light gray backgrounds
    usageNotes: Extremely limited palette focusing on clarity
    saturation: low (functional, not decorative)
    contrast: high (black text on white)
  lineArt:
    style: minimal, functional lines
    weight: consistent, systematic
    color: black or single color
    texture: clean, precise
    edgeTreatment: sharp, clean edges
  lighting:
    type: even, non-dramatic lighting
    direction: consistent, functional
    intensity: clear, readable
    shadows:
      style: minimal or no shadows
      color: light gray
      opacity: very subtle
    highlights: minimal, functional
  rendering:
    technique: precise, systematic layout
    texture: smooth, clean surfaces
    detailLevel: minimal (essential information only)
    finish: matte, functional
  perspective: flat, grid-based layout
  mood:
    overall: objective, clear, systematic
    emotion: clarity, efficiency, neutrality
    tempo: steady, organized
    keywords:
    - objective
    - clear
    - systematic
    - neutral
    - functional
  stylePrecedents:
  - Josef Müller-Brockmann posters
  - Helvetica typeface design