styleName: Symbolism Art Movement Style
description: Late 19th-century art movement that rejected realism in favor of a world of dreams, myths, and the subconscious. Works are full of symbols, mood, and often have a mystical or dreamlike character.
aiPrompts:
  basePrompt: symbolism painting, mythological, dreamlike, mysterious atmosphere, literary themes, femme fatale, spiritual, melancholic, Gustave Moreau style
  negativePrompt: realism, impressionism, objective, mundane, bright and cheerful, direct representation
  styleKeywords:
  - symbolism
  - dreamlike
  - mystical
  - mythological
  - melancholic
visualElements:
  colorPalette:
    primary:
    - deep blues and violets
    - gold and old gold
    - dark greens
    - blood red
    secondary:
    - pearl white
    - ivory shades
    - dark brown
    background: dreamlike landscapes, dark interiors, undefined space
    usageNotes: Colors build mood and have symbolic meaning, need not be realistic.
    saturation: often muted, except for symbolic bright accents
    contrast: medium to high, often with large dark areas
  lineArt:
    style: flowing, elegant contour, but often fading into darkness
    weight: varied, from delicate to strong
    color: integrated with color patches
    texture: smooth, but rich in ornamental details
    edgeTreatment: soft, often blurred edges
  lighting:
    type: mysterious, unnatural, often spotlights or inner glow
    direction: undefined, building atmosphere of mystery
    intensity: low, with dramatic bright points
    shadows:
      style: deep, soft, enveloping figures
      color: dark browns, violets, blues
      opacity: heavy, impenetrable
    highlights: luminous halos, magical glow, golden details
  rendering:
    technique: oil painting with attention to detail but soft modeling
    texture: rich textures of fabrics, jewelry, feathers
    detailLevel: high in symbolic details, background often simplified
    finish: matte or satin, with shimmering accents
  perspective: often flattened, decorative, subordinated to symbolic composition
  mood:
    overall: mysterious, atmospheric, literary
    emotion: melancholy, longing, spirituality, unease
    tempo: slow, contemplative
    keywords:
    - atmospheric
    - mystical
    - dreamlike
    - symbolic
    - decadent
  stylePrecedents:
  - Gustave Moreau
  - Odilon Redon
  - Arnold Böcklin
  - Jacek Malczewski