styleName: Tachisme Style
description: Spontaneous gestural abstraction characterized by drips, blots, and direct paint application with gestural brushwork
aiPrompts:
  basePrompt: tachisme painting, gestural abstraction, spontaneous brushwork, paint drips, blots, direct paint application, art informel
  negativePrompt: geometric abstraction, hard edge painting, figurative elements, planned composition, smooth finish, controlled technique
  styleKeywords:
  - tachisme
  - gestural
  - spontaneous
  - abstract
  - blot
  - drip painting
visualElements:
  colorPalette:
    primary:
    - earthy colors
    - primary colors
    - mixed paint colors
    secondary:
    - black accents
    - white highlights
    - contrasting color spots
    background: raw canvas or color field background
    usageNotes: Intuitive color mixing directly on canvas surface
    saturation: varies from muted earth tones to vibrant accents
    contrast: high contrast between gestural marks and background
  lineArt:
    style: gestural marks and paint drips rather than defined lines
    weight: highly varied from thin drips to thick impasto strokes
    color: direct paint colors from application
    texture: raw energetic texture with varied thickness
    edgeTreatment: irregular accidental edges from spontaneous application
  lighting:
    type: no representational lighting
    direction: paint texture creates dimensional effects
    intensity: created by paint application thickness
    shadows:
      style: dimensional shadows from thick paint (impasto)
      color: darker paint applications
      opacity: varies with paint thickness
    highlights: thick light-colored paint applications
  rendering:
    technique: direct spontaneous paint application (dripping, throwing, gestural marks)
    texture: heavy impasto texture with drips and raw canvas areas
    detailLevel: abstract with high textural complexity
    finish: highly textured raw surface
  perspective: flat abstract space without representational perspective
  mood:
    overall: energetic raw intuitive expression
    emotion: spontaneous expression and gestural freedom
    tempo: dynamic spontaneous energetic
    keywords:
    - spontaneous
    - raw
    - energetic
    - gestural
    - intuitive
    - expressive
  stylePrecedents:
  - Jean-Paul Riopelle gestural abstractions
  - Wols spontaneous compositions
  - Hans Hartung calligraphic gestures