styleName: Utopian Futurism Style
description: Dynamic technological optimism featuring streamlined forms, geometric architecture, integrated advanced technology, and progressive movement aesthetics
aiPrompts:
  basePrompt: utopian future city, streamlined architecture, dynamic geometric forms, technological integration, progressive movement, bright energetic colors, aerodynamic shapes, machine aesthetics
  negativePrompt: dystopian, static, decay, industrial grime, oppression, stagnation, primitive technology
  styleKeywords:
  - utopian futurism
  - dynamic progress
  - technological optimism
  - streamlined forms
  - geometric architecture
  - aerodynamic design
visualElements:
  colorPalette:
    primary:
    - "#5fb7cf"
    - "#5a79c8"
    - "#c0c0c0"
    secondary:
    - "#ffd700"
    - "#40e0d0"
    - "#e6e6fa"
    background: dynamic technological environments with integrated lighting
    usageNotes: Vibrant energetic colors emphasizing technological progress
    saturation: medium-high (energetic, optimistic)
    contrast: medium to high (dynamic, progressive)
  lineArt:
    style: streamlined geometric forms with speed elements
    weight: variable, emphasizing movement and direction
    color: chrome and metallic accents
    texture: sleek technological surfaces
    edgeTreatment: aerodynamic curves and sharp geometric edges
  lighting:
    type: integrated architectural illumination
    direction: dramatic directional with technological sources
    intensity: bright with dynamic contrasts
    shadows:
      style: geometric shadows emphasizing form
      color: cool blue-grays
      opacity: medium for depth and dimension
    highlights: chrome reflections and metallic surfaces
  rendering:
    technique: sleek technological precision
    texture: metallic, glass, and composite materials
    detailLevel: high technological detail integration
    finish: chrome, brushed metal, glass surfaces
  perspective: dynamic compositions with movement emphasis
  mood:
    overall: progressive, optimistic, technologically enthusiastic
    emotion: excitement about future progress, technological wonder
    tempo: dynamic, energetic, forward-moving
    keywords:
    - progressive
    - technological
    - dynamic
    - optimistic
    - energetic
    - futuristic
  stylePrecedents:
  - Antonio Sant'Elia Città Nuova architecture
  - Streamline Moderne design movement
  - Art Deco futuristic elements
  - Apple Store architectural aesthetics
  - Tesla design language
  - THX 1138 technological environments