styleName: Victorian Book Illustration Style
description: Classic 19th century book illustration with wood engravings on boxwood blocks, crosshatching, and period-accurate details
aiPrompts:
  basePrompt: Victorian book illustration, wood engraving, boxwood block, end-grain engraving, detailed line work, 19th century, classical illustration
  negativePrompt: modern, color, loose, abstract, digital
  styleKeywords:
  - Victorian
  - wood engraving
  - boxwood
  - engraving
  - classical
  - detailed
  - 19th century
  - literary
  - white-line
visualElements:
  colorPalette:
    primary:
    - '#000000'
    - '#FFFFFF'
    secondary:
    - sepia tones
    - aged paper
    background: cream or aged paper
    usageNotes: Primarily monochromatic, occasional sepia wash
    saturation: none to minimal
    contrast: high through line density
  lineArt:
    style: precise engraving lines
    weight: very fine, built up in layers
    color: black ink
    texture: crosshatching, stippling
    edgeTreatment: precise, controlled
  lighting:
    type: classical, theatrical
    direction: three-quarter lighting
    intensity: dramatic through line density
    shadows:
      style: built through crosshatching
      color: black line density
      opacity: varied through technique
    highlights: white paper showing through
  rendering:
    technique: wood engraving simulation
    texture: fine line patterns throughout
    detailLevel: extremely high, meticulous
    finish: printed illustration quality
  perspective: classical, accurate
  mood:
    overall: formal, literary, refined
    emotion: dignity, propriety, narrative drama
    tempo: measured, contemplative
    keywords:
    - classical
    - refined
    - literary
    - formal
    - dignified
  stylePrecedents:
  - Gustave Doré
  - John Tenniel
  - George Cruikshank