styleName: Vintage Cartoon Style
description: 1920s-30s cartoon style (rubber hose) with simple bouncy characters, high contrast ink, and film grainy black-and-white aesthetic
aiPrompts:
  basePrompt: 1920s cartoon, rubber hose limbs, pie-cut eyes, black and white animation, Fleischer style
  negativePrompt: modern anime, high detail, realistic shading, color
  styleKeywords:
  - vintage cartoon
  - rubber hose
  - black-and-white
  - retro animation
  - whimsical
visualElements:
  colorPalette:
    primary:
    - black
    - white
    - gray
    secondary:
    - sepia tint
    - light blue tint (optional)
    background: light gray or simple hand-drawn background elements
    usageNotes: Mostly monochrome; slight sepia or bluish cast optional for old film effect
    saturation: none (monochrome) or very low
    contrast: high (strong black ink vs white)
  lineArt:
    style: smooth rubber hose inking
    weight: medium-thick, uniform
    color: black
    texture: clean, with minor wobbles (hand-drawn quality)
    edgeTreatment: rounded, noodle-like curves
  lighting:
    type: flat (no realistic lighting, cel-style fills)
    direction: n/a
    intensity: n/a
    shadows:
      style: simple black shape shadows or none
      color: black
      opacity: solid
    highlights: none (flat fills only)
  rendering:
    technique: hand-drawn cel animation style
    texture: film grain, dust, and scratches
    detailLevel: low (simple, iconic forms)
    finish: matte ink, vintage film look
  perspective: side-on or simple perspective (like early animation frames)
  mood:
    overall: playful, nostalgic, light-hearted
    emotion: joy, silliness
    tempo: bouncy, upbeat
    keywords:
    - nostalgic
    - playful
    - simple
    - old-timey
    - charming
  stylePrecedents:
  - Early Mickey Mouse cartoons
  - Fleischer Studios animation