styleName: Woodcut Style
description: Traditional relief printing technique where images are carved into wood blocks, creating bold contrasts and visible wood grain texture
aiPrompts:
  basePrompt: woodcut print, relief printing, carved wood, bold contrasts, wood grain, block print
  negativePrompt: smooth gradients, photographic detail, soft edges, color painting, digital perfection
  styleKeywords:
  - woodcut
  - relief print
  - carved
  - wood grain
  - block print
visualElements:
  colorPalette:
    primary:
    - black ink
    - paper white
    - single color ink
    secondary:
    - sepia brown
    - dark red
    - deep blue
    background: paper color or simple color
    usageNotes: Limited colors, usually monochromatic or few colors
    saturation: medium (ink colors)
    contrast: very high (carved vs uncarved areas)
  lineArt:
    style: bold carved lines following wood grain
    weight: varies with carving tool, generally bold
    color: ink color (usually black)
    texture: rough carved texture, wood grain visible
    edgeTreatment: rough, hand-carved edges
  lighting:
    type: simplified lighting through carved areas
    direction: basic light indication
    intensity: high contrast (lit vs shadow areas)
    shadows:
      style: solid carved areas (black ink)
      color: ink color
      opacity: solid
    highlights: uncarved areas (paper color)
  rendering:
    technique: relief printing from carved wooden block
    texture: wood grain texture, printing irregularities
    detailLevel: moderate (limited by carving technique)
    finish: matte ink on paper
  perspective: simple, often flattened perspective
  mood:
    overall: bold, traditional, handcrafted
    emotion: strength, tradition, craftsmanship
    tempo: solid, grounded
    keywords:
    - bold
    - traditional
    - handcrafted
    - strong
    - rustic
  stylePrecedents:
  - Japanese ukiyo-e prints
  - German Expressionist woodcuts